### ISSUE TITLE
ProjectParser fails with content including wildcards

### ISSUE THREAD

**Issue by kcamp** [cake-build/cake#1299]
### What You Are Seeing?

Cake.Common.Solution.Project.ProjectParser fails when the *.csproj contains wildcards in a <Content Include="" /> block
### What is Expected?

Cake should not throw an exception.  

Not sure what I might expect with regard to the results.  Attempting to glob/resolve all files included in the pattern might be useful, but not throwing an exception would be the minimum viable
### What version of Cake are you using?

0.16.1
### Are you running on a 32 or 64 bit system?

64
### What environment are you running on?  Windows? Linux? Mac?

Windows
### Are you running on a CI Server?  If so, which one?

No
### How Did You Get This To Happen? (Steps to Reproduce)

Attempted a `Parse(...)` call on any  *.csproj containing the following:

```
<Content Include="app\**" />
```

I have written a failing test here -
https://github.com/kcamp/cake/commit/140e21728a751a808017f9994cc5126ba461295a
### Output Log

``` sh
An error occured when executing task 'Report-Project-References'.
Error: System.ArgumentException: Illegal characters in directory path (*).
Parameter name: path
   at Cake.Core.IO.Path..ctor(String path)
   at Cake.Core.IO.FilePath..ctor(String path)
   at Cake.Core.IO.FilePath.FromString(String path)
   at Cake.Core.IO.FilePath.op_Implicit(String path)
   at Cake.Common.Solution.Project.ProjectParser.<>c__DisplayClass3_1.<Parse>b__27(<>f__AnonymousType8`2 <>h__TransparentIdentifier3)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Cake.Common.Solution.Project.ProjectParser.Parse(FilePath projectPath)
   at Namespace.ProjectReportingParser.ParseProject(FilePath projectPath)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Namespace.ProjectReportingParser.ParseAll(String pattern)
   at Namespace.ProjectReportingAliases.ParseProjectReferences(ICakeContext context, String pattern)
   at Namespace.ProjectReportingAliases.ReportProjectReferences(ICakeContext context, String pattern)
   at Submission#0.<.ctor>b__0()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass4_0.<Does>b__0(ICakeContext context)
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

**Comment by gep13** [comment]
@kcamp we believe that this is no longer an issue.  If this is still the case, please let us know, and we can re-open it.
