### ISSUE TITLE
Addin Framework parsing fails

### ISSUE THREAD

**Issue by aateeque** [cake-build/cake#1328]
### What You Are Seeing?
Error: System.InvalidOperationException: Something went wrong when parsing framework.

### What is Expected?
Script should run withour error

### What version of Cake are you using?
Version 0.16.2+Branch.main.Sha.fb23be463dacfa51c9b19a7cd111149dda7e8c6b

### Are you running on a 32 or 64 bit system?
64-bit

### What environment are you running on?  Windows? Linux? Mac?
Windows 7

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
Attaching debugger to a script that installs any Cake Addin. I am using VS Code and have tried with Visual Studio too

### Output Log

```
Error: System.InvalidOperationException: Something went wrong when parsing framework.
   at Cake.NuGet.V3.NuGetV3ContentResolver.ParseFromDirectoryPath(NuGetFramework current, DirectoryPath path)
   at Cake.NuGet.V3.NuGetV3ContentResolver.GetAddinAssemblies(DirectoryPath path)
   at Cake.NuGet.NuGetContentResolver.GetFiles(DirectoryPath path, PackageReference package, PackageType type)
   at Cake.NuGet.NuGetPackageInstaller.Install(PackageReference package, PackageType type, DirectoryPath path)
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(ScriptAnalyzerResult analyzerResult, DirectoryPath installPath)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.DebugCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

**Comment by devlead** [comment]
@aateeque how does the #addin directive/in you build.cake

**Comment by aateeque** [comment]
@devlead I have `#addin nuget:?package=Cake.ReSharperReports&version=0.3.1`. Same if I replace that package with `Cake.AliaSql` for example

**Comment by mholo65** [comment]
You mentioned using VS Code for debugging, you are the using **Cake.CoreCLR** and not **Cake**, am I correct?

AFAIK, **Cake.ReSharperReports** and **Cake.AliaSql** are .NET 4.5 packages, and does not then work with .NET Core...

**Comment by aateeque** [comment]
@mholo65 I have tried compiling & running latest master in VS 2015 and observe the same behaviour

**Comment by patriksvensson** [comment]
@aateeque Do you have a `cake.config` configuration file? How are you executing the build? Are you using Cake.CoreClr or Cake package?

**Comment by gep13** [comment]
@aateeque can you point us at at complete reproduction of this issue. I.e. Complete cake and bootstrapper you are using, and any other related files.

**Comment by aateeque** [comment]
To narrow down the problem, I have just got `#addin nuget:?package=Cake.AliaSql` in my .cake file which I pass in visual studio debug ass app arg. 

The exception occurs in the `Install Addins` step in `ScriptRunner.Run()`. Specifically, in [`NugetV3ContentResolver line 49`](https://github.com/cake-build/cake/blob/2db6f060b9cfc43e134a23e47429b6e9e44d7825/src/Cake.NuGet/V3/NuGetV3ContentResolver.cs#L49) the `assembly.Path.FullPath` passed in is _C:/dev/code/cake/cake/src/Cake/bin/Debug/Addins/Cake.AliaSql/Cake.AliaSql.dll_ and
`path.GetRelativePath(...)` returns `relative.FullPath` with _Cake.AliaSql.dll_. 

I am sure there is a good reason, but intuitively shouldn't that `relative.FullPath` be the same as `assembly.Path.FullPath` passed earlier?

**Comment by patriksvensson** [comment]
@aateeque No, it should be the relative addin. The error is exactly what it says, it cannot parse the framework from the addin path. The AliasSQL NuGet package does not follow the naming conventions which should be something like `lib/net45/Cake.AliaSql.dll`.

**Comment by aateeque** [comment]
@patriksvensson that makes sense then! Thanks.
Could we change that to a more meaningful message perhaps? "Expected to find TFM in package path, but found none."
