### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly Microsoft.DotNet.InternalAbstractions

### ISSUE THREAD

**Issue by janhartmann** [cake-build/cake#1376]
I'm currently running a build on AppVeyor, with the new .NET Core 1.1. Apperently one of my test projects fail to run.

```
...
Finished executing task: Build
========================================
Tests
========================================
Executing task: Tests
Executing: "C:/Program Files/dotnet/dotnet.exe" test "C:/projects/auth/test/AskCody.Auth.Infrastructure.Tests/project.json" --configuration Release
Project AskCody.Auth (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project AskCody.Auth.Infrastructure (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project AskCody.Auth.Infrastructure.Tests (.NETCoreApp,Version=v1.1) was previously compiled. Skipping compilation.
xUnit.net .NET CLI test runner (64-bit .NET Core win81-x64)
  Discovering: AskCody.Auth.Infrastructure.Tests
  Discovered:  AskCody.Auth.Infrastructure.Tests
  Starting:    AskCody.Auth.Infrastructure.Tests
  Finished:    AskCody.Auth.Infrastructure.Tests
=== TEST EXECUTION SUMMARY ===
   AskCody.Auth.Infrastructure.Tests  Total: 7, Errors: 0, Failed: 0, Skipped: 0, Time: 1.271s
SUMMARY: Total: 1 targets, Passed: 1, Failed: 0.
Executing: "C:/Program Files/dotnet/dotnet.exe" test "C:/projects/auth/test/AskCody.Auth.Server.Tests/project.json" --configuration Release
Project AskCody.Auth (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project AskCody.Auth.Infrastructure (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project AskCody.Auth.Server (.NETCoreApp,Version=v1.1) was previously compiled. Skipping compilation.
Project AskCody.Auth.Server.Tests (.NETCoreApp,Version=v1.1) was previously compiled. Skipping compilation.
Cake.exe : Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find 
the file specified.
At line:1 char:1
+ & "C:\projects\auth\tools\Cake\Cake.exe" "build.cake" -target="AppVey ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled Excep...file specified.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Xunit.Runner.DotNet.Program.GetAvailableRunnerReporters()
   at Xunit.Runner.DotNet.Program.Run(String[] args)
   at Xunit.Runner.DotNet.Program.Main(String[] args)
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
An error occurred when executing task '
Tests'.
Error: 
Cake.Core.CakeException: .NET Core CLI: Process returned an error (exit code -532462766).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSetti
ngs processSettings, Action`1 postAction)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments)
   at Cake.Common.Tools.DotNetCore.Test.DotNetCoreTester.Test(String project, DotNetCoreTestSettings settings)
   at Cake.Common.Tools.DotNetCore.DotNetCoreAliases.DotNetCoreTest(ICakeContext context, String project, DotNetCoreTestSettings settings)
   at Submission#0.<.ctor>b__10()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass5_0.<Does>b__0(ICakeContext context)
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
Command executed with exception:
```

The test projects have the same dependencies, so I am unsure why one of the projects fail. The exception of `Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions` is not a dependency I have anywhere in my code base.

The build script for testing is:

```
Task("Tests")
	.IsDependentOn("Build")
	.Does(() => {
		foreach (var projectJson in GetFiles("./test/**/project.json"))
        {
			DotNetCoreTest(projectJson.FullPath, new DotNetCoreTestSettings
			{
				Configuration = "Release"
			});
		}
    });
```

I am running Cake 0.16.2.

**Comment by devlead** [comment]
Do you have the same issue with latest v0.17.0? Do you have an global.json specifying desired tooling?
Also is the SDK you're using listed by AppVeyor [here](https://www.appveyor.com/docs/installed-software/), if not you'll need to download/bootstrap that yourself, you can see an example how the Cake project does it [here](https://github.com/cake-build/cake/blob/develop/build.ps1#L70)

**Comment by janhartmann** [comment]
My `global.json` is just:

```js
{
  "projects": [ "src", "test" ]
}
```

AppVeyor just yesterday updated the SDK for .NET Core 1.1 as of this issue: https://github.com/appveyor/ci/issues/1176 which is now enabled on the Visual Studio 2015 image.

I'll try to update the Cake version and see what happens.

**Comment by devlead** [comment]
Ok it's a good idea to specify the tooling version in [global.json](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/global-json) i.e.
```json
{
    "sdk": {
        "version": "1.0.0-preview2-003121"
    }
}
```

Especially with the latest preview which isn't compatible with previous ones, you can have multiple SDKs installed but by default it'll pick the latest.

**Comment by janhartmann** [comment]
The build has always succeeded locally, just AppVeyor that can not build a single test project.

I tried adding the SDK version and increment the version in the Cake packages.config to 0.17.0 - same error.

**Comment by janhartmann** [comment]
Actually I am able to reproduce the issue on my localhost when running cake. dotnet.exe halts and crashes during build. I tried debugging it, but so far not coming any closer to the issue.

**Comment by gep13** [comment]
@janhartmann if you run Cake with Diagnostic Verbosity:

http://stackoverflow.com/questions/38658660/how-to-enable-diagnostic-verbosity-for-cake

And then run the dotnet command that is being used directly in the command window, does it also halt and fail the build?

Trying to isolate whether the issue is with cake, or the dotnet cli.

**Comment by janhartmann** [comment]
Yes, it is actually dotnet cli:

```
PS C:\GitHub\auth> dotnet test "C:/GitHub/auth/test/AskCody.Auth.Server.Tests/project.json" --configuration Release
Project AskCody.Auth (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project AskCody.Auth.Infrastructure (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project AskCody.Auth.Server (.NETCoreApp,Version=v1.1) was previously compiled. Skipping compilation.
Project AskCody.Auth.Server.Tests (.NETCoreApp,Version=v1.1) was previously compiled. Skipping compilation.
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Den angivne fil blev ikke fundet
   at Xunit.Runner.DotNet.Program.GetAvailableRunnerReporters()
   at Xunit.Runner.DotNet.Program.Run(String[] args)
   at Xunit.Runner.DotNet.Program.Main(String[] args)
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
PS C:\GitHub\auth>
```

**Comment by janhartmann** [comment]
Or maybe a combination of Xunit - I'll move forward from here and closing this issue.

**Comment by gep13** [comment]
@janhartmann thanks for checking that.  Hope you get it sorted out!

**Comment by devlead** [comment]
Btw wonder if this is related to dotnet/core-setup#275

**Comment by devlead** [comment]
This could be related to
https://twitter.com/bradwilson/status/800571238854733824

**Comment by janhartmann** [comment]
It smells like it. I'll poke around their GitHub issues
