### ISSUE TITLE
NugetPush fails when ApiKey contains a special character

### ISSUE THREAD

**Issue by meichtf** [cake-build/cake#1413]
### What You Are Seeing?

NugetPush fails when the apikey contains a special character like the Escape Character ^

### What is Expected?

Cake.Common.Tools.NuGet.Push.NuGetPusher.cs should probably use a QuotedArgument here: https://github.com/cake-build/cake/blob/08907d1a5d97b66f58c01ae82506280882dcfacc/src/Cake.Common/Tools/NuGet/Push/NuGetPusher.cs#L72

### What version of Cake are you using?
18
### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows 10

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)

My password contains a ^ character and I kept getting back a 401

**Comment by phillipsj** [comment]
What happens when you use your NuGet API Key that is generated.

**Comment by meichtf** [comment]
nuget push mypackage.nupkg myapikey:withspecialChar^  -source mysource
would result in:
Response status code does not indicate success: 400 (Bad Request).

However

nuget push mypackage.nupkg "myapikey:withspecialChar^"  -source mysource

works

**Comment by meichtf** [comment]
NuGetPush writes the following error:

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The underlying connection was clos
ed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connec
tion: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existin
g connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.Net.WebException: The underlying connection was closed: An unexpected error occurred on
 a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was fo
rcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by
 the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()<---
