### ISSUE TITLE
Space in Reference Preprocessor Directive Throws Illegal characters in path

### ISSUE THREAD

**Issue by wleader** [cake-build/cake#1426]
### What You Are Seeing?
adding a preprocessor directive like this:
    #r "path to/assembly.dll"
or:
    #reference "path to/assembly.dll"
results in:
```
    Error: System.ArgumentException: Illegal characters in path.
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.IsPathRooted(String path)
       at Cake.Core.IO.Path..ctor(String path)
       at Cake.Core.IO.FilePath..ctor(String path)
       at Cake.Core.Scripting.Processors.ReferenceDirectiveProcessor.Process(IScriptAnalyzerContext context, String line, String& replacement)
       at Cake.Core.Scripting.Analysis.ScriptAnalyzer.<>c__DisplayClass6_2.<AnalyzeCallback>b__0(LineProcessor p)
       at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
       at Cake.Core.Scripting.Analysis.ScriptAnalyzer.AnalyzeCallback(IScriptAnalyzerContext context)
       at Cake.Core.Scripting.Analysis.ScriptAnalyzerContext.Analyze(FilePath path)
       at Cake.Core.Scripting.Analysis.ScriptAnalyzer.Analyze(FilePath path)
       at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
       at Cake.Commands.BuildCommand.Execute(CakeOptions options)
       at Cake.CakeApplication.Run(CakeOptions options)
       at Cake.Program.Main()
```

### What is Expected?
Assuming the path is valid, the reference should be loaded, if the path is invalid, a file not found exception.

### What version of Cake are you using?
First saw with 0.11.0, updated to 0.17.0 same issue.

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Windows 10 Enterprise

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)

A single line .cake file with a reference as described above can reproduce the problem.

**Comment by wleader** [comment]
Possibly related to https://github.com/cake-build/cake/issues/1389 ?

**Comment by patriksvensson** [comment]
@wleader Yes, it probably is. Will take a look.

**Comment by patriksvensson** [comment]
@wleader It looks like it is. Will try to submit a PR for it tonight.
