### ISSUE TITLE
Fail when script errors

### ISSUE THREAD

**Issue by waynebrantley** [cake-build/cake#1478]
### What You Are Seeing?

  When you have a syntax error in the code, the build script compile fails (of course).  However, the exit code is 0 and no 'error' is reported to build system.   This makes it look like it succeeded.

   In a similar manner.  If the code that runs before any TASK runs throws an exception, it exits with a code of zero and it looks like the build failed.

### What is Expected?
   If the compile fails, exit code should not be zero.    If the script crashes anywhere, should not report an exit code of zero.

### What version of Cake are you using?
0.17

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows 

### Are you running on a CI Server?  If so, which one?
TeamCity

### How Did You Get This To Happen? (Steps to Reproduce)
Create any script that is invalid and try to get cake to run it.

### Output Log
```sh
[09:55:35]	[Step 1/1] Importing namespace System.Text...
[09:55:35]	[Step 1/1] Importing namespace System.Threading.Tasks...
[09:55:35]	[Step 1/1] Compiling build script...
[09:55:35]	[Step 1/1] Error: Roslyn.Compilers.CompilationErrorException: E:/TeamCity/buildAgent/work/1e87de33e7622155/build.cake(177,17): error CS1001: Identifier expected
[09:55:35]	[Step 1/1]    at Roslyn.Scripting.CommonScriptEngine.CompilationError(DiagnosticBag localDiagnostics, DiagnosticBag diagnostics)
[09:55:35]	[Step 1/1]    at Roslyn.Scripting.CommonScriptEngine.Compile(String code, String path, DiagnosticBag diagnostics, Session session, Type delegateType, Type returnType, CancellationToken cancellationToken, Boolean isInteractive, Boolean isExecute, CommonCompilation& compilation, Delegate& factory)
[09:55:35]	[Step 1/1]    at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
[09:55:35]	[Step 1/1]    at Roslyn.Scripting.Session.Execute(String code)
[09:55:35]	[Step 1/1]    at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
[09:55:35]	[Step 1/1]    at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
[09:55:35]	[Step 1/1]    at Cake.Commands.BuildCommand.Execute(CakeOptions options)
[09:55:35]	[Step 1/1]    at Cake.CakeApplication.Run(CakeOptions options)
[09:55:35]	[Step 1/1]    at Cake.Program.Main()
[09:55:35]	[Step 1/1] Process exited with code 0
```
or in the case of program error
```sh
[09:47:00]	[Step 1/1] Error: System.ArgumentException: Invalid version.
[09:47:00]	[Step 1/1] Parameter name: version
[09:47:00]	[Step 1/1]    at Semver.SemVersion.Parse(String version, Boolean strict)
[09:47:00]	[Step 1/1]    at Submission#0..ctor(Session session, Object& submissionResult)
[09:47:00]	[Step 1/1]    at Submission#0.<Factory>(Session session)
[09:47:00]	[Step 1/1]    at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
[09:47:00]	[Step 1/1]    at Roslyn.Scripting.Session.Execute(String code)
[09:47:00]	[Step 1/1]    at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
[09:47:00]	[Step 1/1]    at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
[09:47:00]	[Step 1/1]    at Cake.Commands.BuildCommand.Execute(CakeOptions options)
[09:47:00]	[Step 1/1]    at Cake.CakeApplication.Run(CakeOptions options)
[09:47:00]	[Step 1/1]    at Cake.Program.Main()
[09:47:00]	[Step 1/1] Process exited with code 0
```

**Comment by waynebrantley** [comment]
I put the example call to SymVersion that crashes inside ``Setup()`` and that still didn't report an error.

**Comment by devlead** [comment]
How are you calling Cake from TeamCity? Any error should result in a non zero.

Just tried this:
```cake
Setup(context=>{
    throw new Exception("Bad");
});

Task("Nothing");

RunTarget("Nothing");
```
Result
![image](https://cloud.githubusercontent.com/assets/1647294/22377444/43874c14-e4b2-11e6-9b0a-b00ac4d0cf0f.png)

**Comment by waynebrantley** [comment]
https://github.com/cake-build/cake-teamcity/blob/develop/MR_Cake.xml

''Invoke-Expression "& `"$cakePath`" `"%mr.Cake.script%`" -target=`"%mr.Cake.target%`" -verbosity=`"%mr.Cake.verbosity%`" %mr.Cake.arguments%"``

Is there another way?

**Comment by devlead** [comment]
try adding `;exit $LASTEXITCODE`

For Cake I use:
```PowerShell
.\build.ps1
exit $LASTEXITCODE
```

But if you have the cake exe pre installed and available you should just be able to use a ,net process runner.

**Comment by waynebrantley** [comment]
That did it.
https://github.com/cake-build/cake-teamcity/pull/5
