### ISSUE TITLE
NullReferenceException in closure

### ISSUE THREAD

**Issue by peter-perot** [cake-build/cake#1486]
### What You Are Seeing?

A `NullReferenceException`.

### What is Expected?

`this != null`

### What version of Cake are you using?

0.17.0

### Are you running on a 32 or 64 bit system?

64 bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

No.

## _[Edit: The code below is incorrect. See [this comment](https://github.com/cake-build/cake/issues/1486#issuecomment-276487224) for the correction.]_

```csharp
string mytext = "hello";
Action myaction;

// local block
{
  myaction = () =>
  {
    var t = mytext;  // NullReferenceException
  }
}

myaction();
```

A `NullReferenceException` is thrown since `this` captured in the closure is `null` for some reason.

**Comment by peter-perot** [comment]
**Hint:** This bug only appears if the closure is in a local block.

**Comment by gep13** [comment]
@peter-perot do you also get this issue if you pass the `--Experimental` flag when running Cake?

**Comment by devlead** [comment]
@peter-perot there's a missing semicolon after the delegate declaration, does it work if you add that?

![image](https://cloud.githubusercontent.com/assets/1647294/22464252/384840cc-e7b6-11e6-85ad-335697c8c5c3.png)

**Comment by peter-perot** [comment]
Sorry, guys, I tried to reduce my script to a minimum and made a mistake. Here comes the corrected script to reproduce the bug (**and the bug also appears if I use the `--Experimental` flag**):

```csharp
string mytext = "hello";
Action myaction;

// local block
{
  bool test = true;

  myaction = () =>
  {
    if (test)
    {
      var t = mytext;  // NullReferenceException
    }
  };
}

myaction();
```

When I leave out the `if` block, the script works okay. The same is true when I leave out the _local block braces_.

IOW: This code works okay (the code I accidentally posted first):

```csharp
string mytext = "hello";
Action myaction;

// local block
{
  bool test = true;

  myaction = () =>
  {
    if (test)
    {
      var t = mytext;  // it works
    }
  };
}

myaction();
```

This code works, too:

```csharp
string mytext = "hello";
Action myaction;

bool test = true;

myaction = () =>
{
  if (test)
  {
    var t = mytext;  // it works
  }
};

myaction();
```

The cause of the `NullReferenceException` is that the `this` reference is `null` in the sample which reproduces the bug.

**Comment by peter-perot** [comment]
Two more examples:

This code (with `if (true) { }` block) reproduces the bug:

```csharp
string mytext = "hello";
Action myaction;

if (true)
{
  bool test = true;

  myaction = () =>
  {
    if (test)
    {
      var t = mytext;  // NullReferenceException
    }
  };
}

myaction();
```

This code (sort of an IIFE) works okay again:

```csharp
string mytext = "hello";
Action myaction;

((Action)(() =>
{
  bool test = true;

  myaction = () =>
  {
    if (test)
    {
      var t = mytext;  // it works
    }
  };
}))();

myaction();
```

**Comment by peter-perot** [comment]
And a last one for today:

This example works:

```csharp
string mytext = "hello";
Action myaction;

((Action)(() =>
{
  // local block
  {
    bool test = true;

    myaction = () =>
    {
      if (test)
      {
        var t = mytext;  // it works
      }
    };
  }
}))();

myaction();
```

**Comment by patriksvensson** [comment]
@peter-perot Can you run the script with diagnostic verbosity and post the complete log here?

**Comment by peter-perot** [comment]
Here comes the log:

Running this script...

```csharp
string mytext = "hello";
Action myaction;

// local block
{
  bool test = true;

  myaction = () =>
  {
    if (test)
    {
      var t = mytext;  // NullReferenceException
    }
  };
}

myaction();
```

... produces that log:

```
Preparing to run build script...
Running build script...
Module directory does not exist.
Analyzing build script...
Analyzing D:/Sandbox/Projects/BugRepro/test.cake...
Processing build script...
Creating script session...
Adding reference to mscorlib.dll...
Adding reference to System.Core.dll...
Adding reference to Cake.Core.dll...
Adding reference to Cake.Common.dll...
Adding reference to Cake.exe...
Adding reference to System.dll...
Adding reference to System.Xml.dll...
Adding reference to System.Xml.Linq.dll...
Adding reference to System.Data.dll...
Importing namespace Cake.Common...
Importing namespace Cake.Common.Build...
Importing namespace Cake.Common.Build.AppVeyor...
Importing namespace Cake.Common.Build.AppVeyor.Data...
Importing namespace Cake.Common.Build.BitbucketPipelines...
Importing namespace Cake.Common.Build.BitbucketPipelines.Data...
Importing namespace Cake.Common.Build.Bitrise...
Importing namespace Cake.Common.Build.Bitrise.Data...
Importing namespace Cake.Common.Build.ContinuaCI...
Importing namespace Cake.Common.Build.ContinuaCI.Data...
Importing namespace Cake.Common.Build.GitLabCI...
Importing namespace Cake.Common.Build.GitLabCI.Data...
Importing namespace Cake.Common.Build.GoCD...
Importing namespace Cake.Common.Build.GoCD.Data...
Importing namespace Cake.Common.Build.Jenkins...
Importing namespace Cake.Common.Build.Jenkins.Data...
Importing namespace Cake.Common.Build.TFBuild...
Importing namespace Cake.Common.Build.TFBuild.Data...
Importing namespace Cake.Common.Build.TravisCI...
Importing namespace Cake.Common.Build.TravisCI.Data...
Importing namespace Cake.Common.Diagnostics...
Importing namespace Cake.Common.IO...
Importing namespace Cake.Common.IO.Paths...
Importing namespace Cake.Common.Net...
Importing namespace Cake.Common.Security...
Importing namespace Cake.Common.Solution...
Importing namespace Cake.Common.Solution.Project...
Importing namespace Cake.Common.Solution.Project.Properties...
Importing namespace Cake.Common.Solution.Project.XmlDoc...
Importing namespace Cake.Common.Text...
Importing namespace Cake.Common.Tools...
Importing namespace Cake.Common.Tools.Cake...
Importing namespace Cake.Common.Tools.Chocolatey...
Importing namespace Cake.Common.Tools.Chocolatey.ApiKey...
Importing namespace Cake.Common.Tools.Chocolatey.Config...
Importing namespace Cake.Common.Tools.Chocolatey.Features...
Importing namespace Cake.Common.Tools.Chocolatey.Install...
Importing namespace Cake.Common.Tools.Chocolatey.Pack...
Importing namespace Cake.Common.Tools.Chocolatey.Pin...
Importing namespace Cake.Common.Tools.Chocolatey.Push...
Importing namespace Cake.Common.Tools.Chocolatey.Sources...
Importing namespace Cake.Common.Tools.Chocolatey.Upgrade...
Importing namespace Cake.Common.Tools.DNU...
Importing namespace Cake.Common.Tools.DNU.Build...
Importing namespace Cake.Common.Tools.DNU.Pack...
Importing namespace Cake.Common.Tools.DNU.Restore...
Importing namespace Cake.Common.Tools.DotCover...
Importing namespace Cake.Common.Tools.DotCover.Analyse...
Importing namespace Cake.Common.Tools.DotCover.Cover...
Importing namespace Cake.Common.Tools.DotCover.Report...
Importing namespace Cake.Common.Tools.DotNetCore...
Importing namespace Cake.Common.Tools.DotNetCore.Build...
Importing namespace Cake.Common.Tools.DotNetCore.Execute...
Importing namespace Cake.Common.Tools.DotNetCore.Pack...
Importing namespace Cake.Common.Tools.DotNetCore.Publish...
Importing namespace Cake.Common.Tools.DotNetCore.Restore...
Importing namespace Cake.Common.Tools.DotNetCore.Run...
Importing namespace Cake.Common.Tools.DotNetCore.Test...
Importing namespace Cake.Common.Tools.DupFinder...
Importing namespace Cake.Common.Tools.Fixie...
Importing namespace Cake.Common.Tools.GitLink...
Importing namespace Cake.Common.Tools.GitReleaseManager...
Importing namespace Cake.Common.Tools.GitReleaseManager.AddAssets...
Importing namespace Cake.Common.Tools.GitReleaseManager.Close...
Importing namespace Cake.Common.Tools.GitReleaseManager.Create...
Importing namespace Cake.Common.Tools.GitReleaseManager.Export...
Importing namespace Cake.Common.Tools.GitReleaseManager.Publish...
Importing namespace Cake.Common.Tools.GitReleaseNotes...
Importing namespace Cake.Common.Tools.GitVersion...
Importing namespace Cake.Common.Tools.ILMerge...
Importing namespace Cake.Common.Tools.ILRepack...
Importing namespace Cake.Common.Tools.InnoSetup...
Importing namespace Cake.Common.Tools.InspectCode...
Importing namespace Cake.Common.Tools.MSBuild...
Importing namespace Cake.Common.Tools.MSTest...
Importing namespace Cake.Common.Tools.NSIS...
Importing namespace Cake.Common.Tools.NuGet...
Importing namespace Cake.Common.Tools.NuGet.Install...
Importing namespace Cake.Common.Tools.NuGet.Pack...
Importing namespace Cake.Common.Tools.NuGet.Push...
Importing namespace Cake.Common.Tools.NuGet.Restore...
Importing namespace Cake.Common.Tools.NuGet.SetApiKey...
Importing namespace Cake.Common.Tools.NuGet.SetProxy...
Importing namespace Cake.Common.Tools.NuGet.Sources...
Importing namespace Cake.Common.Tools.NuGet.Update...
Importing namespace Cake.Common.Tools.NUnit...
Importing namespace Cake.Common.Tools.OctopusDeploy...
Importing namespace Cake.Common.Tools.OpenCover...
Importing namespace Cake.Common.Tools.ReportGenerator...
Importing namespace Cake.Common.Tools.ReportUnit...
Importing namespace Cake.Common.Tools.Roundhouse...
Importing namespace Cake.Common.Tools.SignTool...
Importing namespace Cake.Common.Tools.SpecFlow...
Importing namespace Cake.Common.Tools.SpecFlow.StepDefinitionReport...
Importing namespace Cake.Common.Tools.SpecFlow.TestExecutionReport...
Importing namespace Cake.Common.Tools.TextTransform...
Importing namespace Cake.Common.Tools.VSTest...
Importing namespace Cake.Common.Tools.WiX...
Importing namespace Cake.Common.Tools.WiX.Heat...
Importing namespace Cake.Common.Tools.XBuild...
Importing namespace Cake.Common.Tools.XUnit...
Importing namespace Cake.Common.Xml...
Importing namespace Cake.Core...
Importing namespace Cake.Core.Diagnostics...
Importing namespace Cake.Core.IO...
Importing namespace Cake.Core.Scripting...
Importing namespace System...
Importing namespace System.Collections.Generic...
Importing namespace System.IO...
Importing namespace System.Linq...
Importing namespace System.Text...
Importing namespace System.Threading.Tasks...
Compiling build script...
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Submission#0.<>c__DisplayClass0.<.ctor>b__2()
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

**Comment by patriksvensson** [comment]
@peter-perot The reason for that is that `myaction` isn't available in the outer scope.
This code in a regular Console application would fail as well:

```csharp
{
    int nop = 0;
}

nop = nop + 1; // Error: The name 'nop' does not exist in the current context
```

**Comment by peter-perot** [comment]
@patriksvensson: But `myaction` **is** available in the outer scope since it is declared at the beginning of the code.

```csharp
Action myaction;  // declared in outer scope

{
  myaction = ...  // assigned in inner scope
}

myaction();
```

and **not**

```csharp
{
  var myaction = ...  // declared and assigned in inner scope
}

myaction(); // will not compile
```

However – the following code works without an exception when running in a console application, but it will throw an `NullReferenceException` in Cake:

```csharp
using System;

namespace ConsoleApplication
{
  internal class Program
  {
    private static void Main(string[] args)
    {
      string mytext = "hello";
      Action myaction;

      // local block
      {
        bool test = true;

        myaction = () =>
        {
          if (test)
          {
            string t = mytext; // NullReferenceException in CAKE,
                               // but not in console application
          }
        };
      }

      myaction();
    }
  }
}
```

**Comment by patriksvensson** [comment]
@peter-perot Seems like it's a bug in Roslyn scripting I'm afraid. Not much we can do about it :(

**Comment by peter-perot** [comment]
@patriksvensson: Seems there is a similar bug in Roslyn: https://github.com/dotnet/roslyn/issues/16895

Should I file a new issue there?

**Comment by devlead** [comment]
@peter-perot  Sounds reasonable and reference this issue.

**Comment by peter-perot** [comment]
@patriksvensson: I just tried to reproduce the bug with Roslyn to file an issue but here the bug does not appear.

This is the code which throws an exception in Cake:

```csharp
string mytext = "hello";
System.Action myaction;

// local block
{
  bool test = true;

  myaction = () =>
  {
    if (test)
    {
      var t = mytext;  // NullReferenceException
    }
  };
}

myaction();
```

When I use it in Roslyn directly...

``` csharp
CSharpScript.RunAsync(@"string mytext = ""hello"";
System.Action myaction;

// local block
{
  bool test = true;

  myaction = () =>
  {
    if (test)
    {
      var t = mytext;  // NullReferenceException
    }
  };
}

myaction();").Result;
```

... everything works okay.

So the question is: what is different in your usage of the Rosyln engine?

**Comment by devlead** [comment]
@peter-perot which version of Roslyn are you using? Cake v0.20.0 will use latest 2.x could be an Roslyn issue that has been fixed.

**Comment by peter-perot** [comment]
@devlead: I intentionally used an older version, namely 1.1.0, and even this version does not reproduce the bug. So I think there must be some edge case with Cake and Roslyn which produces this bug.

**Comment by wozzo** [comment]
Using cake v0.21.1.0 I'm getting a similar problem when trying to create Tasks within a foreach loop.
`var solutions = GetSolutions();
foreach (var solution in solutions)
{
  Information("Creating tasks for " + solution.Name);

  Task(solution.Name).Does(() => 
  {
    MSBuild(solution.FilePath, msBuildSettings); 
  });
}`
Gives the following error when run

> An error occurred when executing task 'ArtesianCore-only'.
> Error: Object reference not set to an instance of an object.

Confusingly the following works but does not print 1
`  Task(solution.Name + "-only").Does(() => 
  {
    if (solution == null)
      Information("1");
  });`
but the following does not - giving the same error as above
`  Task(solution.Name + "-only").Does(() => 
  {
    if (solution != null)
      Information("1");
  });`

**Comment by wozzo** [comment]
I've since tried adding the experimental flag and it works as expected

**Comment by devlead** [comment]
@peter-perot @wozzo this is now sorted without need for experimental as we unified around a newer version of Roslyn since 0.22.0.
