### ISSUE TITLE
DotNetCoreBuild VS2017 csproj not supported

### ISSUE THREAD

**Issue by mvput** [cake-build/cake#1494]
Trying to build a .NETCore Console Application created with VS2017 RC using cake. Following line is used for executing the build.

`DotNetCoreBuild("./src/ConsoleApplication1/ConsoleApplication1.csproj", settings);`

When running the script the task fails with error:

`An error occurred when executing task 'Build'.
Error: Cake.Core.CakeException: Failed to parse project properties
   at Cake.Incubator.CustomProjectParser.ParseCsProjFile(FilePath projectPath, String config)
   at Cake.Incubator.ProjectParserExtensions.ParseProject(ICakeContext context, FilePath project, String configuration)
   at Submission#0.CopyBuildOutput()
   at Submission#0.<.ctor>b__10()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass5_0.<Does>b__0(ICakeContext context)
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask
task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0.<get_Build>b__0(String target)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()`

Looks like `Cake.Incubator` doesn't support VS2017 new csproj files. The csproj files looks minimalistic compared to previous csproj files.

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
</Project>`

Using the cli with command: `dotnet build src\ConsoleApplication1\ConsoleApplication1.csproj` does work. 

Other `DotNetCore` commands available in cake i didn't test but looks to me it works the same as `DotNetCoreBuild` for parsing projects.

**Comment by gep13** [comment]
@mvput am I right in saying that you are using Cake.Recipe?  Or are you using Cake.Incubator directly?

If the former, then I haven't tested Cake.Recipe on .Net Core Projects, but it is on my radar.  There are likely some assumptions that I have made for .net projects, that won't translate over to .Net core projects.

If the latter, then I think this issue is best raised here: https://github.com/cake-contrib/Cake.Incubator

**Comment by mvput** [comment]
@gep13 Yes i'm using Cake.Recipe. Tested with a minimal build script without Cake.Recipe and seems to work. So problem seems to be with Cake.Incubator.

**Comment by gep13** [comment]
Cake.Recipe attempts to read the csproj file in order to determine project type, to know where to copy output to.  This format is completely different in .net core projects, and may be that Cake.Recipe needs to find another way to do this for .net core.

As I said though, Cake.Recipe has not been tested on .net core projects, and I wouldn't recommend using it for those just yet.

**Comment by gep13** [comment]
Closing this, in favour of https://github.com/cake-contrib/Cake.Incubator/issues/10
