### ISSUE TITLE
Cake Build Unable to Restore 'Microsoft.CodeAnalysis.Scripting' version '1.0.0-rc2'

### ISSUE THREAD

**Issue by martpendle** [cake-build/cake#1584]
### What You Are Seeing?
When Cake attempts to restore packages it fails stating it is unable to find 'Microsoft.CodeAnalysis.Scripting' version '1.0.0-rc2'

### What is Expected?
Cake to restore packages successfully 

### What version of Cake are you using?
0.17.0 but also seen using 0.19.4

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### How Did You Get This To Happen? (Steps to Reproduce)
Run this following command
 .\build.ps1 -Experimental -dryrun -Verbosity Diagnostic

### Attempted Fixes
Updated cake to 0.19.4 in tools\packages.config
Add reference to Microsoft.CodeAnalysis.Scripting 1.1.0 in tools\packages.config
~~~sh
  <package id="Microsoft.CodeAnalysis.Scripting" version="1.1.0" />
~~~

### Output Log
~~~sh
C:\Work Files\Development\Product\Build> .\build.ps1 -Experimental -dryrun -Verbosity Diagnostic
Preparing to run build script...
& "C:\Work Files\Development\Product\Build\tools\Cake\Cake.exe" "build.cake" -target="Default" -configuration="Release" -verbosity="Diagnostic"  -dryrun -experimental
Running build script...
Module directory does not exist.
Analyzing build script...
Analyzing C:/Work Files/Development/Product/Build/build.cake...
Analyzing C:/Work Files/Development/Product/Build/project.cake...
Analyzing C:/Work Files/Development/Product/Build/mobilelocations.cake...
Processing build script...
Installing addins...
Creating directory C:/Work Files/Development/Product/Build/tools/Addins
Installing NuGet package Cake.MSBuildTask...
Executing: "C:/Work Files/Development/Product/Build/tools/nuget.exe" install "Cake.MSBuildTask" -OutputDirectory "C:/Work Files/Development/Product/Build/tools/Addins" -ExcludeVersion -NonInteractive -NoCache
The addin Cake.MSBuildTask will reference Cake.MSBuildTask.dll.
The addin Cake.MSBuildTask will reference Microsoft.Build.Framework.dll.
The addin Cake.MSBuildTask will reference Microsoft.Build.Utilities.v4.0.dll.
Installing NuGet package Cake.FileHelpers...
Executing: "C:/Work Files/Development/Product/Build/tools/nuget.exe" install "Cake.FileHelpers" -OutputDirectory "C:/Work Files/Development/Product/Build/tools/Addins" -ExcludeVersion -NonInteractive -NoCache
The addin Cake.FileHelpers will reference Cake.FileHelpers.dll.
Creating script session...
Using prerelease build of Roslyn.
Downloading and installing Roslyn (experimental)...
Installing packages (using https://packages.nuget.org/api/v2)...
Downloading package Microsoft.CodeAnalysis.Scripting (1.0.0-rc2)...
Error: System.InvalidOperationException: An error has occurred. ---> System.Data.Services.Client.DataServiceQueryException: An error occurred while processing this request. ---> System.Data.Services.Client.DataServiceClientException: <?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code /><m:message xml:lang="en-US">An error has occurred.</m:message></m:error>
   at System.Data.Services.Client.QueryResult.Execute()
   at System.Data.Services.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   --- End of inner exception stack trace ---
   at System.Data.Services.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at NuGet.DataServiceQueryWrapper`1.Execute[TResult](Func`1 action)
   --- End of inner exception stack trace ---
   at NuGet.DataServiceQueryWrapper`1.Execute[TResult](Func`1 action)
   at NuGet.DataServiceQueryWrapper`1.<GetAll>d__7.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.PackageRepositoryExtensions.ResolveDependencyCore(IPackageRepository repository, PackageDependency dependency, IPackageConstraintProvider constraintProvider, Boolean allowPrereleaseVersions, Boolean preferListedPackages, DependencyVersion dependencyVersion)
   at NuGet.InstallWalker.ResolveDependency(PackageDependency dependency)
   at NuGet.PackageWalker.Walk(IPackage package)
   at NuGet.PackageWalker.Walk(IPackage package)
   at NuGet.PackageWalker.Walk(IPackage package)
   at NuGet.InstallWalker.ResolveOperations(IPackage package)
   at NuGet.PackageManager.Execute(IPackage package, IPackageOperationResolver resolver)
   at NuGet.PackageManager.InstallPackage(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at Cake.Scripting.Roslyn.Nightly.RoslynNightlyScriptSessionFactory.Install(SemanticVersion version)
   at Cake.Scripting.Roslyn.Nightly.RoslynNightlyScriptSessionFactory.CreateSession(IScriptHost host)
   at Cake.Scripting.Roslyn.RoslynScriptEngine.CreateSession(IScriptHost host, IDictionary`2 arguments)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.DryRunCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
~~~

**Comment by gep13** [comment]
Duplicate of:

https://github.com/cake-build/cake/issues/1583
https://github.com/cake-build/cake/issues/1582

This is an issue with NuGet.org

**Comment by gep13** [comment]
@martpendle seems like NuGet is having lots of issues today.  I suspect what you are seeing is a symptom of that.

**Comment by martpendle** [comment]
@gep13 Thanks, didn't even think of that being an issue, the unlisted package threw me off on a different path
