### ISSUE TITLE
Debugging cake scripts in visual studio code and using #load

### ISSUE THREAD

**Issue by robgha01** [cake-build/cake#1589]
Its simply not working no scripts are loaded see the zip in this issue https://github.com/cake-build/cake/issues/1588 i get messages indicating that it cant find variables etc that live inside the #load script.

**Comment by mholo65** [comment]
@robgha01 is it only when debugging or does it also happen when running the script without debugging? Could you paste verbose log of what is happening (i.e. set `--Verbosity Diagnostic`). Thanks!

**Comment by robgha01** [comment]
@mholo65 i get this when i debug
```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Private.CoreLib.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'd:\Workspaces\BlueLeet\BlueLeet.UCodeFirst\Build\tools\Cake.CoreCLR\Cake.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\mscorlib.dll'. Cannot find or open the PDB file.
Loaded 'd:\Workspaces\BlueLeet\BlueLeet.UCodeFirst\Build\tools\Cake.CoreCLR\Cake.Core.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'd:\Workspaces\BlueLeet\BlueLeet.UCodeFirst\Build\tools\Cake.CoreCLR\Cake.Common.dll'. Cannot find or open the PDB file.
Loaded 'd:\Workspaces\BlueLeet\BlueLeet.UCodeFirst\Build\tools\Cake.CoreCLR\Cake.NuGet.dll'. Cannot find or open the PDB file.
Loaded 'd:\Workspaces\BlueLeet\BlueLeet.UCodeFirst\Build\tools\Cake.CoreCLR\Autofac.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Runtime.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.IO.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Reflection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Globalization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Linq.Expressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Reflection.TypeExtensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Reflection.Emit.ILGeneration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Reflection.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Reflection.Emit.Lightweight.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Reflection.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Runtime.InteropServices.RuntimeInformation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.IO.FileSystem.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```
When i remove the --debug it seams to be the same:
```
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.IO.UnmanagedMemoryStream.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Compiling build script...
Loaded 'd:\Workspaces\BlueLeet\BlueLeet.UCodeFirst\Build\tools\Cake.CoreCLR\Microsoft.CodeAnalysis.CSharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Dynamic.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Threading.Tasks.Parallel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Resources.ResourceManager.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.4\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Error: Microsoft.CodeAnalysis.Scripting.CompilationErrorException: d:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(7,19): error CS0103: The name 'tmpDir' does not exist in the current context
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync(String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Cake.Scripting.XPlat.DefaultXPlatScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
The program '[24932] Cake.dll' has exited with code 1 (0x1).
```

**Comment by robgha01** [comment]
The build scripts looks like this: https://gist.github.com/robgha01/6393b59e11694f6f135e95c5c93b376b

**Comment by mholo65** [comment]
@robgha01 what happens if you move `#load nuget:?package=BlueLeet.Build` to the top in `build.cake`?

**Comment by robgha01** [comment]
@mholo65 i get the same error:
```
D:\Workspaces\BlueLeet\BlueLeet.UCodeFirst\Build>dotnet ../.tools/Cake.CoreCLR/Cake.dll build.cake --verbosity=diagnostic --debug
Module directory does not exist.
Performing debug...
Attach debugger to process 28688 to continue
Debugger attached
Analyzing build script...
Analyzing D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake...
Processing build script...
Adding reference to System.Private.CoreLib.ni.dll...
Adding reference to System.Linq.Expressions.dll...
Adding reference to Cake.Core.dll...
Adding reference to Cake.Common.dll...
Adding reference to System.Runtime.dll...
Adding reference to System.Diagnostics.Debug.dll...
Adding reference to System.Collections.dll...
Adding reference to System.Runtime.Extensions.dll...
Adding reference to System.Reflection.dll...
Adding reference to System.Console.dll...
Adding reference to System.Runtime.Loader.dll...
Adding reference to Microsoft.Extensions.DependencyModel.dll...
Adding reference to System.IO.dll...
Adding reference to System.Text.RegularExpressions.dll...
Adding reference to System.Reflection.Primitives.dll...
Adding reference to System.Diagnostics.Process.dll...
Adding reference to System.IO.FileSystem.dll...
Adding reference to System.IO.FileSystem.Primitives.dll...
Adding reference to System.Text.Encoding.dll...
Adding reference to System.Collections.Concurrent.dll...
Adding reference to Microsoft.Win32.Registry.dll...
Adding reference to System.Linq.dll...
Adding reference to System.Globalization.dll...
Adding reference to System.Threading.dll...
Adding reference to System.Reflection.Extensions.dll...
Adding reference to System.Runtime.InteropServices.dll...
Adding reference to System.Reflection.TypeExtensions.dll...
Adding reference to System.Runtime.InteropServices.RuntimeInformation.dll...
Adding reference to System.ComponentModel.TypeConverter.dll...
Adding reference to System.Xml.ReaderWriter.dll...
Adding reference to System.Xml.XmlDocument.dll...
Adding reference to System.Security.Cryptography.Primitives.dll...
Adding reference to System.Xml.XDocument.dll...
Adding reference to System.Runtime.Serialization.Json.dll...
Adding reference to System.Net.Http.dll...
Adding reference to System.Threading.Tasks.dll...
Adding reference to System.IO.Compression.dll...
Adding reference to System.Runtime.Serialization.Primitives.dll...
Adding reference to System.Xml.XPath.XmlDocument.dll...
Adding reference to System.Text.Encoding.Extensions.dll...
Adding reference to System.Security.Cryptography.Algorithms.dll...
Adding reference to System.IO.Compression.ZipFile.dll...
Adding reference to System.Net.Primitives.dll...
Importing namespace Cake.Common...
Importing namespace Cake.Common.Build...
Importing namespace Cake.Common.Build.AppVeyor...
Importing namespace Cake.Common.Build.AppVeyor.Data...
Importing namespace Cake.Common.Build.Bamboo...
Importing namespace Cake.Common.Build.Bamboo.Data...
Importing namespace Cake.Common.Build.BitbucketPipelines...
Importing namespace Cake.Common.Build.BitbucketPipelines.Data...
Importing namespace Cake.Common.Build.Bitrise...
Importing namespace Cake.Common.Build.Bitrise.Data...
Importing namespace Cake.Common.Build.ContinuaCI...
Importing namespace Cake.Common.Build.ContinuaCI.Data...
Importing namespace Cake.Common.Build.GitLabCI...
Importing namespace Cake.Common.Build.GitLabCI.Data...
Importing namespace Cake.Common.Build.GoCD...
Importing namespace Cake.Common.Build.GoCD.Data...
Importing namespace Cake.Common.Build.Jenkins...
Importing namespace Cake.Common.Build.Jenkins.Data...
Importing namespace Cake.Common.Build.MyGet...
Importing namespace Cake.Common.Build.TeamCity...
Importing namespace Cake.Common.Build.TFBuild...
Importing namespace Cake.Common.Build.TFBuild.Data...
Importing namespace Cake.Common.Build.TravisCI...
Importing namespace Cake.Common.Build.TravisCI.Data...
Importing namespace Cake.Common.Diagnostics...
Importing namespace Cake.Common.IO...
Importing namespace Cake.Common.IO.Paths...
Importing namespace Cake.Common.Net...
Importing namespace Cake.Common.Security...
Importing namespace Cake.Common.Solution...
Importing namespace Cake.Common.Solution.Project...
Importing namespace Cake.Common.Solution.Project.Properties...
Importing namespace Cake.Common.Solution.Project.XmlDoc...
Importing namespace Cake.Common.Text...
Importing namespace Cake.Common.Tools...
Importing namespace Cake.Common.Tools.Cake...
Importing namespace Cake.Common.Tools.Chocolatey...
Importing namespace Cake.Common.Tools.Chocolatey.ApiKey...
Importing namespace Cake.Common.Tools.Chocolatey.Config...
Importing namespace Cake.Common.Tools.Chocolatey.Features...
Importing namespace Cake.Common.Tools.Chocolatey.Install...
Importing namespace Cake.Common.Tools.Chocolatey.New...
Importing namespace Cake.Common.Tools.Chocolatey.Pack...
Importing namespace Cake.Common.Tools.Chocolatey.Pin...
Importing namespace Cake.Common.Tools.Chocolatey.Push...
Importing namespace Cake.Common.Tools.Chocolatey.Sources...
Importing namespace Cake.Common.Tools.Chocolatey.Uninstall...
Importing namespace Cake.Common.Tools.Chocolatey.Upgrade...
Importing namespace Cake.Common.Tools.DotCover...
Importing namespace Cake.Common.Tools.DotCover.Analyse...
Importing namespace Cake.Common.Tools.DotCover.Cover...
Importing namespace Cake.Common.Tools.DotCover.Merge...
Importing namespace Cake.Common.Tools.DotCover.Report...
Importing namespace Cake.Common.Tools.DotNetCore...
Importing namespace Cake.Common.Tools.DotNetCore.Build...
Importing namespace Cake.Common.Tools.DotNetCore.Execute...
Importing namespace Cake.Common.Tools.DotNetCore.Pack...
Importing namespace Cake.Common.Tools.DotNetCore.Publish...
Importing namespace Cake.Common.Tools.DotNetCore.Restore...
Importing namespace Cake.Common.Tools.DotNetCore.Run...
Importing namespace Cake.Common.Tools.DotNetCore.Test...
Importing namespace Cake.Common.Tools.DupFinder...
Importing namespace Cake.Common.Tools.Fixie...
Importing namespace Cake.Common.Tools.GitLink...
Importing namespace Cake.Common.Tools.GitReleaseManager...
Importing namespace Cake.Common.Tools.GitReleaseManager.AddAssets...
Importing namespace Cake.Common.Tools.GitReleaseManager.Close...
Importing namespace Cake.Common.Tools.GitReleaseManager.Create...
Importing namespace Cake.Common.Tools.GitReleaseManager.Export...
Importing namespace Cake.Common.Tools.GitReleaseManager.Publish...
Importing namespace Cake.Common.Tools.GitReleaseNotes...
Importing namespace Cake.Common.Tools.GitVersion...
Importing namespace Cake.Common.Tools.ILMerge...
Importing namespace Cake.Common.Tools.ILRepack...
Importing namespace Cake.Common.Tools.InnoSetup...
Importing namespace Cake.Common.Tools.InspectCode...
Importing namespace Cake.Common.Tools.MSBuild...
Importing namespace Cake.Common.Tools.MSTest...
Importing namespace Cake.Common.Tools.NSIS...
Importing namespace Cake.Common.Tools.NuGet...
Importing namespace Cake.Common.Tools.NuGet.Add...
Importing namespace Cake.Common.Tools.NuGet.Init...
Importing namespace Cake.Common.Tools.NuGet.Install...
Importing namespace Cake.Common.Tools.NuGet.Pack...
Importing namespace Cake.Common.Tools.NuGet.Push...
Importing namespace Cake.Common.Tools.NuGet.Restore...
Importing namespace Cake.Common.Tools.NuGet.SetApiKey...
Importing namespace Cake.Common.Tools.NuGet.SetProxy...
Importing namespace Cake.Common.Tools.NuGet.Sources...
Importing namespace Cake.Common.Tools.NuGet.Update...
Importing namespace Cake.Common.Tools.NUnit...
Importing namespace Cake.Common.Tools.OctopusDeploy...
Importing namespace Cake.Common.Tools.OpenCover...
Importing namespace Cake.Common.Tools.ReportGenerator...
Importing namespace Cake.Common.Tools.ReportUnit...
Importing namespace Cake.Common.Tools.Roundhouse...
Importing namespace Cake.Common.Tools.SignTool...
Importing namespace Cake.Common.Tools.SpecFlow...
Importing namespace Cake.Common.Tools.SpecFlow.StepDefinitionReport...
Importing namespace Cake.Common.Tools.SpecFlow.TestExecutionReport...
Importing namespace Cake.Common.Tools.TextTransform...
Importing namespace Cake.Common.Tools.WiX...
Importing namespace Cake.Common.Tools.WiX.Heat...
Importing namespace Cake.Common.Tools.VSTest...
Importing namespace Cake.Common.Tools.VSWhere...
Importing namespace Cake.Common.Tools.VSWhere.All...
Importing namespace Cake.Common.Tools.VSWhere.Latest...
Importing namespace Cake.Common.Tools.VSWhere.Legacy...
Importing namespace Cake.Common.Tools.VSWhere.Product...
Importing namespace Cake.Common.Tools.XBuild...
Importing namespace Cake.Common.Tools.XUnit...
Importing namespace Cake.Common.Xml...
Importing namespace Cake.Core...
Importing namespace Cake.Core.Diagnostics...
Importing namespace Cake.Core.IO...
Importing namespace Cake.Core.Scripting...
Importing namespace System...
Importing namespace System.Collections.Generic...
Importing namespace System.IO...
Importing namespace System.Linq...
Importing namespace System.Text...
Importing namespace System.Threading.Tasks...
Compiling build script for debugging...
Error: Cake.Core.CakeException: Error occurred when compiling: D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(9,19): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(9,5): error CS0103: The name 'RequireFolder' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(10,19): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(10,5): error CS0103: The name 'RequireFolder' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(18,52): error CS0103: The name 'projectName' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(18,24): error CS0103: The name 'projectRoot' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(19,23): error CS0103: The name 'projectRoot' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(20,31): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(21,27): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(25,73): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(26,75): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(33,67): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(34,66): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(37,47): error CS0103: The name 'projectName' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(37,19): error CS0103: The name 'projectRoot' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(37,79): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(40,28): error CS0103: The name 'projectName' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(42,59): error CS0103: The name 'configuration' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(42,77): error CS0103: The name 'projectName' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(42,51): error CS0103: The name 'FromBin' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(44,48): error CS0103: The name 'projectName' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(44,63): error CS0103: The name 'packageVersion' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(44,21): error CS0103: The name 'CreateNuGetPackSettings' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(45,26): error CS0103: The name 'projectName' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(46,29): error CS0103: The name 'projectName' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(47,5): error CS1656: Cannot assign to 'Description' because it is a 'method group'
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(56,27): error CS0103: The name 'projectName' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(65,50): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(66,50): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(67,50): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(68,47): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(70,29): error CS0103: The name 'tmpDir' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(74,50): error CS0103: The name 'projectName' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(74,65): error CS0103: The name 'packageVersion' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(74,23): error CS0103: The name 'CreateNuGetPackSettings' does not exist in the current context
D:/Workspaces/BlueLeet/BlueLeet.UCodeFirst/Build/build.cake(84,38): error CS0103: The name 'targetOutput' does not exist in the current context
   at Cake.Scripting.XPlat.DebugXPlatScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.DebugCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

**Comment by robgha01** [comment]
@mholo65 i tested with this: `#load "../.tools/BlueLeet.Build/content/base.cake"` and now the script is getting included and i dont get that error so the problem is #load is not updated for the Cake.CoreCLR ? it must be missing for some reason or someting may need to get fixed for it to work in CLR ? @gep13 you know anything about this ?

**Comment by gep13** [comment]
@robgha01 if you are using Cake.CoreCLR then you can only use addins that are built for .net core. Some of the addins that you are using don't support .net core yet.

**Comment by mholo65** [comment]
@robgha01 does it work when not using `Cake.CoreCLR`?

**Comment by robgha01** [comment]
@gep13 @mholo65 yes it works if i dont use the CoreCLR but the #load is still not including the base script it it because im using addins that are not supported ?
