### ISSUE TITLE
ToolResolutionStrategy fails unexpectedly with Cake.LongPath.Module

### ISSUE THREAD

**Issue by kcamp** [cake-build/cake#1607]
### What You Are Seeing?
Cake build fails to install nuget packages via `#load` or `#addin` with a fatal error. `The directory name is invalid`

### What is Expected?
I expect any issues to be sidestepped and the build to complete.

### What version of Cake are you using?
0.19.4

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows8

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
This is 100% environmental and occurs on a single developer machine.  I cannot repro this or even determine what value (in `%PATH%`) it is failing on in writing some ad hoc unit tests to try to diagnose.

### Output Log
~~~sh
An error occurred when executing task 'Restore-Nuget-Packages'.
Error: System.IO.IOException: The directory name is invalid.

   at Pri.LongPath.Common.ThrowIOError(Int32 errorCode, String maybeFullPath)
   at Pri.LongPath.FileSystemInfo.Refresh()
   at Pri.LongPath.FileInfo.get_Exists()
   at Cake.Core.IO.FileSystemExtensions.Exist(IFileSystem fileSystem, FilePath path)
   at Cake.Core.Tooling.ToolResolutionStrategy.LookInPath(String tool)
   at Cake.Core.Tooling.ToolResolutionStrategy.Resolve(IToolRepository repository, String tool)
   at Cake.Core.Tooling.ToolLocator.Resolve(String tool)
   at Cake.Core.Tooling.Tool`1.GetToolPathUsingToolService(TSettings settings)
   at Cake.Core.Tooling.Tool`1.GetToolPath(TSettings settings)
   at Cake.Core.Tooling.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processS
ettings)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings
, Action`1 postAction)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments)
   at Cake.Common.Tools.NuGet.Restore.NuGetRestorer.Restore(FilePath targetFilePath, NuGetRestoreSettings settings)
   at Cake.Common.Tools.NuGet.NuGetAliases.NuGetRestore(ICakeContext context, FilePath targetFilePath, NuGetRestoreSetti
ngs settings)
   at Cake.Common.Tools.NuGet.NuGetAliases.NuGetRestore(ICakeContext context, IEnumerable`1 targetFilePaths, NuGetRestor
eSettings settings)
   at Submission#0.<.ctor>b__12()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass5_0.<Does>b__0(ICakeContext context)
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask
task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session sessio
n, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
~~~

The failure is ultimately coming from the Cake.LongPath.Module 0.3.0 implementation.
As a what-if scenario, I build the module with a fix in place:
~~~cs
internal sealed class LongPathFile : IFile
...snipped...    
public bool Exists
{
    get
    {
        try
        {
            return File.Exists;
        }
        catch (IOException)
        {
            return false;
        }
    }
}
~~~

This definitely solves the problem.  Looking at the source of the Pri.LongPath,
 it seems like it is undesirable to just mute any exceptions coming out of here for the sake of tool resolution,  particularly as it seems very specific/opinionated.
(see the `Refresh` method --
 https://github.com/peteraritchie/LongPath/blob/master/Pri.LongPath/FileSystemInfo.cs#L304)

It seems that it would be more preferable, instead, to make the `ToolResolutionStrategy` a bit more resilient, instead.

Something like this:

```
foreach (var pathDir in _path)
{
    var file = pathDir.CombineWithFilePath(tool);
    try{
        if (_fileSystem.Exist(file))
        {
            return file.MakeAbsolute(_environment);
         }
    } catch { /* keep going /* }
}
```

If you agree, i can put together a PR easily enough.  Thanks!

**Comment by patriksvensson** [comment]
Fixed via #1608
