### ISSUE TITLE
DupFinder failing with 'The filename or extension is too long'

### ISSUE THREAD

**Issue by flcdrg** [cake-build/cake#1623]
### What You Are Seeing?

Calling `DupFinder(@"**/*.cs");` fails with "Error: The filename or extension is too long"

### What is Expected?

DupFinder should run without error. 

JetBrains DupFinder.exe already handles wildcard expansion correctly. I don't think the current implementation is correct that Cake is trying to do this on DupFinder's behalf.

Alternatively, there should be a way to pass in the wildcard so it is passed untouched through to DupFinder.exe

### What version of Cake are you using?
0.19.5

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### How Did You Get This To Happen? (Steps to Reproduce)

Solution has projects which include `node_modules` deep directory hierarchies.

### Output Log

```
Error: System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Cake.Core.IO.ProcessRunner.Start(FilePath filePath, ProcessSettings settings)
   at Cake.Core.Tooling.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processS
ettings)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings
, Action`1 postAction)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments)
   at Cake.Common.Tools.DupFinder.DupFinderRunner.Run(IEnumerable`1 filePaths, DupFinderSettings settings)
   at Cake.Common.Tools.DupFinder.DupFinderAliases.DupFinder(ICakeContext context, String pattern, DupFinderSettings set
tings)
   at Submission#0.<.ctor>b__32()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass5_0.<Does>b__0(ICakeContext context)
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask
task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session sessio
n, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

**Comment by flcdrg** [comment]
Calling `.\caketools\JetBrains.ReSharper.CommandLineTools\tools\dupfinder.exe **/*.cs` directly does not exhibit this error

**Comment by devlead** [comment]
This looks like an .NET issue, triggered by absolute path to the tool.

You could verify this by using the `subst` command to the `JetBrains.ReSharper.CommandLineTools` folder, i.e. something like:
```PowerShell
subst R: C:\temp\dev\gh\cake-build\cake\tools\JetBrains.ReSharper.CommandLineTools\
```
And setting the [ToolPath](http://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/F6956DA8) property on the [DupFinderSettings](http://cakebuild.net/api/Cake.Common.Tools.DupFinder/DupFinderSettings/) class if you use the [DupFinder(string pattern, DupFinderSettings settings)](http://cakebuild.net/api/Cake.Common.Tools.DupFinder/DupFinderAliases/8B4465AC) alias/overload.
Something like this
```cake
DupFinder(@"**/*.cs", new DupFinderSettings { ToolPath = "R:/tools...." });
```

If that works we at least know what's the issue.

**Comment by flcdrg** [comment]
Either that or the expanded wildcards results in  too many files being passed as arguments

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by flcdrg** [comment]
Just confirming that this is problem with the arguments, not the toolpath.

I figured out a workaround by using `ArgumentCustomization = args=>args.Append(@"**/*.cs")`, and when calling DupFinder with a path to a known small set of .cs files - eg. `DupFinder(@"Subfolder\*.cs", settings);`

That runs without error.
