### ISSUE TITLE
Unable to DeSerialize FilePath Object from JSON format

### ISSUE THREAD

**Issue by jnhaffey** [cake-build/cake#1657]
### What You Are Seeing?
System.ArgumentNullException: 'Value cannot be null.' an exception being thrown when trying to deserialize json object that contains a FilePath Object

### What is Expected?
I should be able to deserialize an object that contains a FilePath object in it.

### What version of Cake are you using?
19.5

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
Create a class that has a property that is a FilePath.  Serialise the object to JSON (file or string).  Try to deserialize the JSON (file or string) and the exception is thrown with the following stack trace:

```
"   at Cake.Core.IO.Path..ctor(String path)
   at Cake.Core.IO.FilePath..ctor(String path)
   at Void .ctor(System.String)(Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Submission#0.Project.BuildProjectFileHashCollection(ICakeContext context) in D:/Personal/GitHub/StACS/build/project.cake:line 67
   at Submission#0.Parameters.Initialize(ICakeContext context, ICollection`1 gitDiffs) in D:/Personal/GitHub/StACS/build/parameters.cake:line 26
   at Submission#0.<.ctor>b__2(ICakeContext context) in D:/Personal/GitHub/StACS/build.cake:line 30
   at Cake.Core.DefaultExecutionStrategy.PerformSetup(Action`1 action, ICakeContext context)
   at Cake.Core.CakeEngine.PerformSetup(IExecutionStrategy strategy, ICakeContext context)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)"
```

I believe the issue at hand is the fact that the FilePath does not have a parameterless constructor.

**Comment by devlead** [comment]
`FilePath` and `DirectoryPath` doesn't have an default constructor by design as it gives type safety within Cake for paths, that said it's fully possible to achieve what your after using a custom serializer.

Example cake file doing this:
```cake
#addin "Newtonsoft.Json"
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

class FilePathConverter : PathConverter<FilePath>
{
    protected override FilePath ToPath(string path)
    {
        return new FilePath(path);
    }
}

class DirectoryPathConverter : PathConverter<DirectoryPath>
{
    protected override DirectoryPath ToPath(string path)
    {
        return new DirectoryPath(path);
    }
}

abstract class PathConverter<T> : JsonConverter where T : Cake.Core.IO.Path
{
    public override bool CanConvert(Type objectType)
    {
        return (objectType == typeof(T));
    }

    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
    {
        if (reader.TokenType == JsonToken.Null) return null;

        JObject jo = JObject.Load(reader);
        var fullPath = (string)jo["FullPath"];
        T path = ToPath(fullPath);
        return path;
    }

    protected virtual T ToPath(string path)
    {
        return null;
    }

    public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
    {
        var path = value as T;
        if (path != null)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("FullPath");
            serializer.Serialize(writer, path.FullPath);
            writer.WriteEndObject();
        }
    }
}

var filePaths = new FilePath[] {
    File("file.txt"),
    MakeAbsolute(File("./file.cs")),
    null
};

var directoryPaths = new DirectoryPath[] {
    Directory("dir1"),
    MakeAbsolute(Directory("./dir2")),
    null
};


JsonSerializerSettings settings = new JsonSerializerSettings();
settings.Converters.Add(new FilePathConverter());
settings.Converters.Add(new DirectoryPathConverter());
settings.Formatting = Formatting.Indented;

var filePathsJson       = JsonConvert.SerializeObject(filePaths, settings);
var directoryPathJson   = JsonConvert.SerializeObject(directoryPaths, settings);

Information(filePathsJson);
Information(directoryPathJson);


var filePathsDeserialized = JsonConvert.DeserializeObject<FilePath[]>(filePathsJson, settings);
var directoryPathsDeserialized = JsonConvert.DeserializeObject<DirectoryPath[]>(directoryPathJson, settings);

foreach(var filePath in filePathsDeserialized)
{
    Information(filePath);
}

foreach(var directoryPath in directoryPathsDeserialized)
{
    Information(directoryPath);
}
```

It will output something like below
![image](https://user-images.githubusercontent.com/1647294/27528424-9cffc988-5a50-11e7-9eeb-5cc73d97d524.png)

**Comment by devlead** [comment]
Closing this issue due to inactivity, if this still an issue please reopen this issue.
