### ISSUE TITLE
Addin Dependencies are not referenced

### ISSUE THREAD

**Issue by nlowe** [cake-build/cake#1884]
### What You Are Seeing?

In the latest released version of cake you are supposed to be able to have cake install addin dependencies by using the `--nuget_useinprocessclient=true` flag and adding `&loaddependencies=true` to the end of the `#addin` directive. It appears these dependencies are restored to disk but are never referenced which cause an exception to be thrown when they are used by the addin.

### What is Expected?

* If I add `--nuget_useinprocessclient=true` to my `cake.exe` flags
  * And I add `&loaddependencies=true` to my addin directive
    * Then Cake will
      1. Download all dependencies of my addin recursively
      2. Reference these dependencies or ensure they are downloaded to a location that will be searched when my addin is loaded

### What version of Cake are you using?

```
~/Projects/cake-addin-deps [master]$ .\tools\cake\Cake.exe --version

             +##   #;;'
             #;;#  .+;;;;+,
             '+;;#;,+';;;;;'#.
             ++'''';;;;;;;;;;# ;#;
            ##';;;;++'+#;;;;;'.   `#:
         ;#   '+'';;;;;;;;;'#`       #.
      `#,        .'++;;;;;':..........#
    '+      `.........';;;;':.........#
   #..................+;;;;;':........#
   #..................#';;;;;'+''''''.#
   #.......,:;''''''''##';;;;;'+'''''#,
   #''''''''''''''''''###';;;;;;+''''#
   #''''''''''''''''''####';;;;;;#'''#
   #''''''''''''''''''#####';;;;;;#''#
   #''''''''''''''''''######';;;;;;#'#
   #''''''''''''''''''#######';;;;;;##
   #''''''''''''''''''########';;;;;;#
   #''''''''''''++####+;#######';;;;;;#
   #+####':,`             ,#####';;;;;;'
                              +##'''''+.
   ___      _          ___       _ _     _
  / __\__ _| | _____  / __\_   _(_) | __| |
 / /  / _` | |/ / _ \/__\// | | | | |/ _` |
/ /___ (_| |   <  __/ \/  \ |_| | | | (_| |
\____/\__,_|_|\_\___\_____/\__,_|_|_|\__,_|

                             Version 0.23.0+Branch.main.Sha.67afe72f1c21a8a3cfd96d3969fb2591d62f37ff
```

### Are you running on a 32 or 64 bit system?

Windows 10 x64

### What environment are you running on?  Windows? Linux? Mac?

Windows 10 x64

### Are you running on a CI Server?  If so, which one?

n/a

### How Did You Get This To Happen? (Steps to Reproduce)

I am developing an addin that references [`BouncyCastle`](https://www.nuget.org/packages/BouncyCastle/) and discovered that dependencies were not being installed for my addin. After reading up on #1848, I tried to use the new in-process nuget client which did install the dependencies but still does not reference them.

I have created an example repo: [nlowe/cake-addin-deps](https://github.com/nlowe/cake-addin-deps) and uploaded my dummy addin to [nuget.org](https://www.nuget.org/packages/Cake.DummyAddin/)

I am not sure if this is because of how `BouncyCastle` is packaged or if this is a problem with cake itself. I'm going to try pushing a different version of the `Cake.Dummy` package that references a different dependency.

### Output Log

[Full Gist](https://gist.github.com/nlowe/3504f47647fba35a2b9b364c228402a7)

```
Error: System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942' or one of its dependencies. The system cannot find the file specified.
   at addin.addin.Foo(ICakeContext ctx)
   at Submission#0.Foo()
   at Submission#0.<<Initialize>>b__0_0()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass8_0.<Does>b__0(ICakeContext x)
   at Cake.Core.ActionTask.<Execute>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTargetAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942' or one of its dependencies. The system cannot find the file specified.
File name: 'BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942'
   at addin.addin.Foo(ICakeContext ctx)
   at Submission#0.Foo()
   at Submission#0.<<Initialize>>b__0_0()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass8_0.<Does>b__0(ICakeContext x)
   at Cake.Core.ActionTask.<Execute>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTargetAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
```

Restored Addins:

```
tools/Addins/
├── BouncyCastle.1.8.1
│   ├── BouncyCastle.1.8.1.nupkg
│   ├── bouncycastle.nuspec
│   ├── lib
│   │   └── BouncyCastle.Crypto.dll
│   └── Readme.txt
├── Cake.Core.0.23.0
│   ├── Cake.Core.0.23.0.nupkg
│   ├── cake.core.nuspec
│   └── lib
│       ├── net46
│       │   ├── Cake.Core.dll
│       │   └── Cake.Core.xml
│       └── netstandard1.6
│           ├── Cake.Core.dll
│           └── Cake.Core.xml
└── Cake.DummyAddin.1.0.0
    ├── Cake.DummyAddin.1.0.0.nupkg
    ├── cake.dummyaddin.nuspec
    └── lib
        ├── net46
        │   └── addin.dll
        └── netstandard1.6
            └── addin.dll
```

**Comment by nlowe** [comment]
I've looked at a few other addins and they seem to bundle their dependencies in their `nupkg`'s so they don't hit this issue. I'm not sure how to do this with the new `csproj` format (or if it's even possible or the right solution).

**Comment by mholo65** [comment]
@nlowe problem is how `BouncyCastle` is packaged. The [`NuGetContentresolver`](https://github.com/cake-build/cake/blob/develop/src/Cake.NuGet/NuGetContentResolver.cs) in Cake doesn't support that structure. The TFM folder is missing under `lib` and instead the `dll` is placed there directly. 

The issue is not in In-process NuGet. I'd bet you'll see the same issue with conventional NuGet by just adding `#addin BouncyCastle` to your Cake file.

@cake-build/cake-team thoughts? Should we fix, or should `BouncyCastle` fix their package? I'd vote for the latter.

**Comment by nlowe** [comment]
Good to know. Also I should probably point out, I think the Bouncy Castle package I'm referencing is community contributed and maintained (The only official way I see to get it on their site is to download a zip of the dll's) so I'm not sure who I'd need to reach out to. I could try the maintainers listed on nuget.org

**Comment by devlead** [comment]
@mholo65 package should be corrected yes.
@nlowe yip reach out using the form on nuget.org should be a good first step.

**Comment by nlowe** [comment]
Cool. Thanks for the speedy responses guys, much appreciated.
