### ISSUE TITLE
NuspecTransformer does not find the 'package' root element when xmlns is set.

### ISSUE THREAD

**Issue by vktr** [cake-build/cake#198]
I'm running into a problem when trying to run `NuGetPack` on a manually generated `.nuspec` file that has the `xmlns` attribute set according to the [Nuspec reference documentation](http://docs.nuget.org/create/nuspec-reference).

Example nuspec [straight from the NuGet docs](http://docs.nuget.org/create/nuspec-reference#user-content-examples-of-nuspec-files),

```xml
<?xml version="1.0" encoding="utf-8"?>

<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>sample</id>
    <version>1.2.3</version>
    <authors>Kim Abercrombie, Franck Halmaert</authors>
    <description>Sample exists only to show a sample .nuspec file.</description>
    <language>en-US</language>
    <projectUrl>http://xunit.codeplex.com/</projectUrl>
    <licenseUrl>http://xunit.codeplex.com/license</licenseUrl>
  </metadata>
</package>
```

Using the following Cake script,

```csharp
Task("Test")
    .Does(() =>
    {
        NuGetPack("./sample.nuspec", new NuGetPackSettings
        {
            BasePath = ".",
            OutputDirectory = "."
        });
    });

RunTarget("Test");
```

Fails with the following stack trace,

```
Cake.Core.CakeException: Nuspec file is missing package root.
   at Cake.Common.Tools.NuGet.Pack.NuspecTransformer.GetPackageElement(XmlDocument document)
   at Cake.Common.Tools.NuGet.Pack.NuspecTransformer.FindOrCreateElement(XmlDocument document, XmlNamespaceManager ns, String name)
   at Cake.Common.Tools.NuGet.Pack.NuspecTransformer.Transform(XmlDocument document, NuGetPackSettings settings)
   at Cake.Common.Tools.NuGet.Pack.NuspecProcessor.Process(FilePath nuspecFilePath, NuGetPackSettings settings)
   at Cake.Common.Tools.NuGet.Pack.NuGetPacker.Pack(FilePath nuspecFilePath, NuGetPackSettings settings)
   at Cake.Common.Tools.NuGet.NuGetAliases.NuGetPack(ICakeContext context, FilePath nuspecFilePath, NuGetPackSettings settings)
   at Submission#0.<.ctor>b__24()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass4.<Does>b__3(ICakeContext context)
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(String code)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath script, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(IEnumerable`1 args)
```

The nuspec packs fine using the nuget command line tool.

**Comment by patriksvensson** [comment]
Will take a look at this later tonight.
