### ISSUE TITLE
Explicitly running Task that is skipped by criteria throws an error

### ISSUE THREAD

**Issue by ubbeK** [cake-build/cake#2018]
The following code throws exception
```csharp
Task("foo").WithCriteria(() => false).Does(() =>{});
RunTarget("foo");
```
```
Error: System.AggregateException: One or more errors occurred. ---> Cake.Core.CakeException: Could not reach target 'foo' since it was skipped due to a criteria.
   at Cake.Core.CakeEngine.ShouldTaskExecute(ICakeContext context, CakeTask task, Boolean isTarget) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 213
   at Cake.Core.CakeEngine.<RunTargetAsync>d__18.MoveNext() in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext() in C:\projects\cake\src\Cake\Scripting\BuildScriptHost.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 173
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Scripting\Roslyn\RoslynScriptSession.cs:line 128
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 212
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 35
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 74
---> (Inner Exception #0) Cake.Core.CakeException: Could not reach target 'foo' since it was skipped due to a criteria.
   at Cake.Core.CakeEngine.ShouldTaskExecute(ICakeContext context, CakeTask task, Boolean isTarget) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 213
   at Cake.Core.CakeEngine.<RunTargetAsync>d__18.MoveNext() in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext() in C:\projects\cake\src\Cake\Scripting\BuildScriptHost.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 173
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()<---
```

but this works fine
```csharp
Task("foo").IsDependentOn("bar");
Task("bar").WithCriteria(() => false).Does(() =>{});
RunTarget("foo");
```

**Is this a bug or feature?**

Why not log exactly what would happen
```
========================================
foo
========================================
Skipping task: foo

Task                            Duration
----------------------------------------------------
foo                             Skipped
----------------------------------------------------
Total:                          00:00:00.0000000
```

### What version of Cake are you using?
0.25.0
### Are you running on a 32 or 64 bit system?
64 bit
### What environment are you running on?  Windows? Linux? Mac?
Windows 10
### Are you running on a CI Server?  If so, which one?
No

**Comment by devlead** [comment]
@ubbeK that is per design. If you really want an explicit task to execute, and we can't do that,  we consider that a failed work flow.

**Comment by ubbeK** [comment]
Closing as answered
