### ISSUE TITLE
After updating VS 2017 to 15.6.3: Could not load type 'Microsoft.Build.Logging.ProfilerLogger'

### ISSUE THREAD

**Issue by tompazourek** [cake-build/cake#2091]
I just updated to latest version of Visual Studio 2017 (15.6.3) that was just released and my Cake builds started crashing (when restoring NuGet packages or running the build task).

This is the snippet of the log:

```
MSBuild auto-detection: using msbuild version '15.6.82.30579' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.

Unhandled Exception: System.TypeLoadException: Could not load type 'Microsoft.Build.Logging.ProfilerLogger' from assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage)
   at System.Exception.ToString()
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

I'm using Cake 0.26.1 and building on Windows 10, it's a full .NET Framework 4.7.1 app, old csproj structure.

**Is this a Cake issue, or should I look for help somewhere else? Can you help?**

Thanks for your time.

**Comment by patriksvensson** [comment]
@tompazourek Doesn't sounds like a Cake issue, but hard to know without the actual build script. Can you run the build with diagnostic verbosity and paste the build log here? Thanks.

**Comment by tompazourek** [comment]
@patriksvensson Thanks for getting back to me. Unfortunately, I'm afraid I cannot assist more at this point because I decided to uninstall Visual Studio 15.6.3 and revert back to an older version again. I really needed to get some work done, and this was the only solution.

Maybe somebody else will experience the same issue and will follow up with more information, the 15.6.3 is a brand new release, and it's possible that more people will have the same issue when they update. Or I may try updating to 15.6.3 again when I've got a bit more time to experiment to pinpoint this issue.

In the meantime, there's some more development related to this in the mentioned [Visual Studio Developer Community ticket](https://developercommunity.visualstudio.com/content/problem/214894/vs-2017-update-v1561-v1562-msbuild-crashes.html). Right now, it looks like it might be solved by removing some MSBuild assemblies from the GAC.

**Comment by devlead** [comment]
VSWHere can be used with cake too
https://cakebuild.net/blog/2017/03/vswhere-and-visual-studio-2017-support
