### ISSUE TITLE
Cake.Common.Tools.NuGet fails in Cake.Tool on Linux/macOS

### ISSUE THREAD

**Issue by qayshp** [cake-build/cake#2283]
### What You Are Seeing?
When running Cake as a global dotnet tool (invoked as `dotnet cake build.cake {args}`) with a script trying to use [`Cake.Common.Tools.NuGet.NuGetAliases.NuGetList(ICakeContext, string)`](https://cakebuild.net/api/Cake.Common.Tools.NuGet/NuGetAliases/20FD7D58) from Linux, we get `System.ComponentModel.Win32Exception: Exec format error`.

From the stack trace this seems to be caused by the call to `Run` from [v0.30.0#Cake.Common.Tools.NuGet.NuGetList#L69-L70](https://github.com/cake-build/cake/blob/v0.30.0/src/Cake.Common/Tools/NuGet/List/NuGetList.cs#L69-L70) which leads to [v0.30.0#Cake.Core.Tooling.Tool#L90-L126](https://github.com/cake-build/cake/blob/v0.30.0/src/Cake.Core/Tooling/Tool.cs#L90-L126).

Unfortunately I'm not yet familiar enough with cake, so it's unclear to me if the executable name of `NuGet.exe` in this case is coming from [v0.30.0#Cake.Common.Tools.NuGet.NuGetTool.cs](https://github.com/cake-build/cake/blob/v0.30.0/src/Cake.Common/Tools/NuGet/NuGetTool.cs#L56) or [v0.30.0#Cake.Core.IO.NuGet.NuGetToolResolver.cs](https://github.com/cake-build/cake/blob/v0.30.0/src/Cake.Core/IO/NuGet/NuGetToolResolver.cs#L70)

### What is Expected?
[`Cake.Common.Tools.NuGet.NuGetAliases.NuGetList(ICakeContext, string)`](https://cakebuild.net/api/Cake.Common.Tools.NuGet/NuGetAliases/20FD7D58) to work, as expected from a build script on Linux when invoked using the Cake.Tool dotnet tool.

Perhaps mistakenly, from the [0.30.0 blog post](https://cakebuild.net/blog/2018/08/cake-v0.30.0-released) we had thought that mono might no longer be required for cake.

Doing a bit of mucking around with the nuget.exe we've downloaded, I can get this to run by creating a shell script that executes nuget through mono and getting cake to use that.

~~~sh
mv $NUGET_EXE ${NUGET_EXE}2
export NUGET_EXE=$NUGET_EXE
echo "#! /bin/bash
mono ${NUGET_EXE}2 \$@
" > $NUGET_EXE
~~~

### What version of Cake are you using?
0.30.0

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Linux and macOS

### Are you running on a CI Server?  If so, which one?
Yes, using Docker as part of an internal pipeline using gitlab and gitlab-ci.

### How Did You Get This To Happen? (Steps to Reproduce)
I don't have a public repro of this issue at the moment, but can create one if needed.

### Output Log
~~~sh
dotnet cake build.cake -verbosity=diagnostic -configuration=Debug -target=VersionCheck
NuGet.config not found.
Analyzing build script...
Analyzing /ciuser/project/build.cake...

....

Executing: /ciuser/project/.tools/nuget.exe list "CompanyName.PackageName" -Verbosity Normal -NonInteractive
An error occurred when executing task 'VersionCheck'.
Executing custom task teardown action (VersionCheck)...

----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Error: System.AggregateException: One or more errors occurred. (Exec format error) ---> System.ComponentModel.Win32Exception: Exec format error
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Cake.Core.IO.ProcessRunner.Start(FilePath filePath, ProcessSettings settings) in C:\projects\cake\src\Cake.Core\IO\ProcessRunner.cs:line 83
   at Cake.Core.Tooling.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 215
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 101
   at Cake.Common.Tools.NuGet.List.NuGetList.List(String packageId, NuGetListSettings settings) in C:\projects\cake\src\Cake.Common\Tools\NuGet\List\NuGetList.cs:line 72
   at Submission#0.NuGetList(String packageId, NuGetListSettings settings)
   at Submission#0.<<Initialize>>b__0_13()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass20_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 82
   at Cake.Core.CakeTask.Execute(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTask.cs:line 125
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context) in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 87
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 336
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 284
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 247
   at Cake.Scripting.BuildScriptHost.RunTargetAsync(String target) in C:\projects\cake\src\Cake\Scripting\BuildScriptHost.cs:line 47
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 191
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Scripting\Roslyn\RoslynScriptSession.cs:line 129
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 212
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 73
---> (Inner Exception #0) System.ComponentModel.Win32Exception (8): Exec format error
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Cake.Core.IO.ProcessRunner.Start(FilePath filePath, ProcessSettings settings) in C:\projects\cake\src\Cake.Core\IO\ProcessRunner.cs:line 83
   at Cake.Core.Tooling.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 215
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 101
   at Cake.Common.Tools.NuGet.List.NuGetList.List(String packageId, NuGetListSettings settings) in C:\projects\cake\src\Cake.Common\Tools\NuGet\List\NuGetList.cs:line 72
   at Submission#0.NuGetList(String packageId, NuGetListSettings settings)
   at Submission#0.<<Initialize>>b__0_13()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass20_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 82
   at Cake.Core.CakeTask.Execute(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTask.cs:line 125
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context) in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 87
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 336
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 284
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 247
   at Cake.Scripting.BuildScriptHost.RunTargetAsync(String target) in C:\projects\cake\src\Cake\Scripting\BuildScriptHost.cs:line 47
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 191
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)<---

ERROR: Job failed: error executing remote command: command terminated with non-zero exit code: Error executing in Docker Container: 1
~~~

**Comment by devlead** [comment]
NuGet.exe is a full framework executable and requires either  .NET Framework on Windows or Mono on unix.

.NET Core Global tools are executing under the .NET Core Runtime, which can run Full framework executables on Windows as Windows natively supports it.

**Comment by qayshp** [comment]
Right, I'm sure it works well on Windows. But using the .NET Core Global tool on Linux doesn't have the same benefit.
I don't mind still having Mono installed, but it would be helpful if the tool either knew to use Mono when not on Windows and executing a process like NuGet, or use a different way of getting the information it needs. For example, `#load nuget:?package=foo&version=1.0.0` directives work when executing the Global Tool as above, without mono.

**Comment by devlead** [comment]
@qayshp if they would make the NuGet.exe available as a .NET Tool it would be a lot easier as .NET tools provide a native shim. So those can easily just be made to work and be executed without the need for mono. 

All tools that are natively available on Linux will just work fine i.e. all the .NET CLI aliases, as there's a native dotnet binary made for each platform.

We just released the .NET tool and will see where we can make the experience better, and we'll take contributions to do so.

I.e. for the octopus deploy cli there's now a .NET tool and we've added that to the tool resolution so that will be available and just work with the next release of Cake.

If the nuget.exe was made available as a .NET tool we could add that to the tool resolution here
https://github.com/cake-build/cake/blob/5e7716a04a0751ccf8e4cdf117a3120264ec6fc2/src/Cake.Common/Tools/NuGet/NuGetTool.cs#L54-L57
