### ISSUE TITLE
Null Reference exception when building project

### ISSUE THREAD

**Issue by coxp** [cake-build/cake#241]
Hi,

Am I missing a step when attempting to compile the solution? I've done a fresh clone of the repository and executed the build.ps1 script but I get a Null Reference Exception when it attempts to execute the Cake script. I get the following 

```
Compiling build script...
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.InitializerDimensions(BoundArrayInitialization init)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitAllElementInitializers(ArrayTypeSymbol arrayType, BoundArrayInit
ialization inits, Boolean skipConstants)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitVectorInitializers(ArrayTypeSymbol arrayType, BoundArrayInitiali
zation inits)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArrayCreationExpression(BoundArrayCreation expression, Boolean u
sed)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArgument(BoundExpression argument, RefKind refKind)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArguments(ReadOnlyArray`1 arguments, ReadOnlyArray`1 parameters)

   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitCallExpression(BoundCall call, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitBlockStatement(BoundBlock block)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.Generate()
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.Run(MethodSymbol meth, BoundStatement block, ILBuilder builder, Modu
le module, DiagnosticBag diagnostics, Boolean optimize, Boolean emitSequencePoints)
   at Roslyn.Compilers.CSharp.Compiler.GenerateMethodBody(TypeCompilationState compilationState, MethodSymbol method, Bo
undStatement block, DiagnosticBag diagnostics, Boolean optimize, Boolean emitSequencePoints, Func`2 mapFileNameToDebugDo
c, ReadOnlyArray`1 namespaceScopes)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.ProcessGeneratedMethods(TypeCompilationState compilationState)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.CompileNamedType(NamedTypeSymbol symbol)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.<>c__DisplayClass6.<VisitNamedType>b__4()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.WaitForWorkers()
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.CompileAllMethodBodies(Compilation compilation, Module moduleBeingBuilt
, Boolean generateDebugInfo, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Roslyn.Compilers.CSharp.Compiler.CompileAllMethodBodies(Compilation compilation, Module moduleBeingBuilt, Boolean
generateDebugInfo, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Roslyn.Compilers.CSharp.Compilation.Emit(ModuleBuilder moduleBuilder, IAssemblyLoader assemblyLoader, Func`2 assem
blySymbolMapper, CancellationToken cancellationToken, Boolean recoverOnError, ReadOnlyArray`1& compiledAssemblyImage)
   at Roslyn.Compilers.CSharp.Compilation.CommonEmit(ModuleBuilder moduleBuilder, IAssemblyLoader assemblyLoader, Func`2
 assemblySymbolMapper, CancellationToken cancellationToken, Boolean recoverOnError, ReadOnlyArray`1& compiledAssemblyIma
ge)
   at Roslyn.Scripting.CommonScriptEngine.TryEmitSubmission(CommonCompilation compilation, DiagnosticBag diagnostics, Ty
pe delegateType, Boolean collectible, CancellationToken cancellationToken, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.Compile(String code, String path, DiagnosticBag diagnostics, Session session,
Type delegateType, Type returnType, CancellationToken cancellationToken, Boolean isInteractive, Boolean isExecute, Commo
nCompilation& compilation, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session sessio
n, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.RoslynScriptSession.Execute(String code)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath script, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(IEnumerable`1 args)
```

**Comment by devlead** [comment]
Do you have VS2015 installed? If so try launching cake.exe with the -experimental option so it uses the latest Roslyn bits.

**Comment by coxp** [comment]
Yes, I only have VS 2015 installed and my current build system (UpperCuT) doesn't support it.

Adding -experimental=`"true`" option, fixed the issue.

Thanks.

**Comment by devlead** [comment]
Excellent, VS2015 installs.Net 4.6 which strangely isn't compatible with previously released Roslyn bits.
