### ISSUE TITLE
Broken heat.exe in package WiX with version=3.11.1

### ISSUE THREAD

**Issue by techtim** [cake-build/cake#2441]
### What You Are Seeing?
Broken heat.exe in package WiX with version=3.11.1

**heat.exe : error HEAT0001 : An error occurred loading a configuration file: The parameter 'exePath' is invalid.**

### What is Expected?
Creation of wxs file
### What version of Cake are you using?
0.32.1
### Are you running on a 32 or 64 bit system?
64
### What environment are you running on?  Windows? Linux? Mac?
Windows
### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
Tested in two projects one  netcoreapp2.2, another netcoreapp2.1 (https://github.com/wieslawsoltes/Core2D)
In "Core2D\src\Core2D.UI.Avalonia" 
- ` dotnet publish -c Release -f netcoreapp2.1`
- make build.cake and build.ps1 files
- paste to build.cake 
```
#tool nuget:?package=WiX&version=3.11.1
var fileWXS = File("./Core2d.wxs");
DirectoryPath path = (DirectoryPath)Directory("./bin/AnyCPU/Release/netcoreapp2.1/publish");
WiXHeat(path, fileWXS, WiXHarvestType.Dir);
```
- ./build

### Output Log
~~~sh
Preparing to run build script...
Running build script...
heat.exe : error HEAT0001 : An error occurred loading a configuration file: The parameter 'exePath' is invalid.
Parameter name: exePath

Exception Type: System.Configuration.ConfigurationErrorsException

Stack Trace:
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   at Microsoft.Tools.WindowsInstallerXml.AppCommon.ReadConfiguration(StringCollection extensions)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Heat.Run(String[] args)
~~~

**Comment by techtim** [comment]
got same error running .\tools\WiX.3.11.1\tools\heat.exe , tried other versions with the same result, other *.exe works

**Comment by techtim** [comment]
Broke only on local machine, on CI everything is fine. Solved this by installing Wix3.11 , adding its bin to environment path and deleting heat.exe from Cakes tools Wix folder
