### ISSUE TITLE
"Getting Started" build.cake fails with VS 2015 installed

### ISSUE THREAD

**Issue by natificent** [cake-build/cake#245]
I just started playing around with cake. My work machine doesn't have VS 2015 installed, and the basic build.cake from the getting started works fine.

I tried running it from my home machine and was getting an object ref exception, so I turned up the logging to Diagnostic. I'm getting an exception from Roslyn:

Trying to find nuget.exe in path
INFO: Could not find files for the given pattern(s).
Installing 'Cake 0.3.2'.
Successfully installed 'Cake 0.3.2'.
Creating script session...
Downloading and installing Roslyn...
Installing package...
Copying files...
Copying Roslyn.Compilers.CSharp.dll...
Copying Roslyn.Compilers.dll...
Deleting installation directory...
Processing build.cake...
Adding reference to mscorlib.dll...
Adding reference to System.dll...
Adding reference to System.Core.dll...
Adding reference to System.Data.dll...
Adding reference to System.Xml.dll...
Adding reference to System.Xml.Linq.dll...
Adding reference to Cake.Core.dll...
Adding reference to Cake.Common.dll...
Adding reference to Cake.exe...
Importing namespace Cake.Common...
Importing namespace Cake.Common.Build...
Importing namespace Cake.Common.Diagnostics...
Importing namespace Cake.Common.IO...
Importing namespace Cake.Common.IO.Paths...
Importing namespace Cake.Common.Security...
Importing namespace Cake.Common.Solution...
Importing namespace Cake.Common.Solution.Project...
Importing namespace Cake.Common.Solution.Project.Properties...
Importing namespace Cake.Common.Solution.Project.XmlDoc...
Importing namespace Cake.Common.Text...
Importing namespace Cake.Common.Tools.Cake...
Importing namespace Cake.Common.Tools.ILMerge...
Importing namespace Cake.Common.Tools.MSBuild...
Importing namespace Cake.Common.Tools.MSTest...
Importing namespace Cake.Common.Tools.NSIS...
Importing namespace Cake.Common.Tools.NuGet...
Importing namespace Cake.Common.Tools.NuGet.Install...
Importing namespace Cake.Common.Tools.NuGet.Pack...
Importing namespace Cake.Common.Tools.NuGet.Push...
Importing namespace Cake.Common.Tools.NuGet.Restore...
Importing namespace Cake.Common.Tools.NuGet.SetApiKey...
Importing namespace Cake.Common.Tools.NuGet.Sources...
Importing namespace Cake.Common.Tools.NuGet.Update...
Importing namespace Cake.Common.Tools.NUnit...
Importing namespace Cake.Common.Tools.SignTool...
Importing namespace Cake.Common.Tools.WiX...
Importing namespace Cake.Common.Tools.XUnit...
Importing namespace Cake.Common.Xml...
Importing namespace Cake.Core...
Importing namespace Cake.Core.Diagnostics...
Importing namespace Cake.Core.IO...
Importing namespace Cake.Core.Scripting...
Importing namespace System...
Importing namespace System.Collections.Generic...
Importing namespace System.IO...
Importing namespace System.Linq...
Importing namespace System.Text...
Importing namespace System.Threading.Tasks...
Compiling build script...
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.InitializerDimensions(BoundArrayInitialization init)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitAllElementInitializers(ArrayTypeSymbol arrayType, BoundArrayInitialization inits, Boolean skipConstants)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitVectorInitializers(ArrayTypeSymbol arrayType, BoundArrayInitialization inits)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArrayCreationExpression(BoundArrayCreation expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArgument(BoundExpression argument, RefKind refKind)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArguments(ReadOnlyArray`1 arguments, ReadOnlyArray`1 parameters)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitCallExpression(BoundCall call, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitBlockStatement(BoundBlock block)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.Generate()
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.Run(MethodSymbol meth, BoundStatement block, ILBuilder builder, Module module, DiagnosticBag diagnostics, Boolean optimize, Boolean emitSequencePoints)
   at Roslyn.Compilers.CSharp.Compiler.GenerateMethodBody(TypeCompilationState compilationState, MethodSymbol method, BoundStatement block, DiagnosticBag diagnostics, Boolean optimize, Boolean emitSequencePoints, Func`2 mapFileNameToDebugDoc, ReadOnlyArray`1 namespaceScopes)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.ProcessGeneratedMethods(TypeCompilationState compilationState)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.CompileNamedType(NamedTypeSymbol symbol)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.<>c__DisplayClass6.<VisitNamedType>b__4()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.WaitForWorkers()
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.CompileAllMethodBodies(Compilation compilation, Module moduleBeingBuilt, Boolean generateDebugInfo, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Roslyn.Compilers.CSharp.Compiler.CompileAllMethodBodies(Compilation compilation, Module moduleBeingBuilt, Boolean generateDebugInfo, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Roslyn.Compilers.CSharp.Compilation.Emit(ModuleBuilder moduleBuilder, IAssemblyLoader assemblyLoader, Func`2 assemblySymbolMapper, CancellationToken cancellationToken, Boolean recoverOnError, ReadOnlyArray`1& compiledAssemblyImage)
   at Roslyn.Compilers.CSharp.Compilation.CommonEmit(ModuleBuilder moduleBuilder, IAssemblyLoader assemblyLoader, Func`2 assemblySymbolMapper, CancellationToken cancellationToken, Boolean recoverOnError, ReadOnlyArray`1& compiledAssemblyImage)
   at Roslyn.Scripting.CommonScriptEngine.TryEmitSubmission(CommonCompilation compilation, DiagnosticBag diagnostics, Type delegateType, Boolean collectible, CancellationToken cancellationToken, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.Compile(String code, String path, DiagnosticBag diagnostics, Session session, Type delegateType, Type returnType, CancellationToken cancellationToken, Boolean isInteractive, Boolean isExecute, CommonCompilation& compilation, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.RoslynScriptSession.Execute(String code)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath script, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(IEnumerable`1 args)

**Comment by devlead** [comment]
Try launching cake.exe with the -experimental option so it uses the latest Roslyn bits.
VS2015 installs.Net 4.6 which isn't compatible with previously released Roslyn bits.

**Comment by natificent** [comment]
Awesome, works perfectly now. Thanks for the quick reply.

**Comment by devlead** [comment]
Excellent, please let us know if you any more issues.
