### ISSUE TITLE
Cake.CoreCLR fails to load module

### ISSUE THREAD

**Issue by flcdrg** [cake-build/cake#2579]
### What You Are Seeing?
Cake fails to download Cake Module package

### What is Expected?
Cake should download module

### What version of Cake are you using?
0.34.1
### Are you running on a 32 or 64 bit system?
64
### What environment are you running on?  Windows? Linux? Mac?
Windows

### How Did You Get This To Happen? (Steps to Reproduce)

`build.cake` has content similar to this:
```
#module nuget:https://www.myget.org/F/flcdrg/?package=Cake.BuildSystems.Module&version=0.32.1-usestagingdirect0001
```

Using Cake.CoreCLR like this:
```
dotnet .\tools\Cake.CoreCLR\Cake.dll --bootstrap --verbosity=diagnostic
```

### Output Log
```
Module directory does not exist.                                                                                        
NuGet Config not specified. Will use NuGet default mechanism for resolving it.                                          Analyzing C:/dev/git/Project/build.cake...                                                                                                                           
Installing modules...                                                                                                   
Error: Cake.Core.CakeException: Failed to install module 'Cake.BuildSystems.Module'.                                       
  at Cake.Core.Scripting.ScriptProcessor.InstallPackages(IReadOnlyCollection`1 modules, DirectoryPath installPath, PackageType packageType) in C:\projects\cake\src\Cake.Core\Scripting\ScriptProcessor.cs:line 217
  at Cake.Commands.BootstrapCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BootstrapCommand.cs:line 57                                                                                                               
  at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
  at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 73
```

**Comment by devlead** [comment]
It should work if you add prerelease parameter to directive

I.e:
```cake
#module nuget:https://www.myget.org/F/flcdrg/?package=Cake.BuildSystems.Module&version=0.32.1-usestagingdirect0001&prerelease
```

**Comment by flcdrg** [comment]
Yes, that did the trick.

How odd that this wasn't required for the non CoreCLR version.
