### ISSUE TITLE
When using the path "./" or ".\" to retrieve a directory, an error stating that the path is not of a legal form is thrown by the .NET implementation.

### ISSUE THREAD

**Issue by Meertman** [cake-build/cake#2647]
### What You Are Seeing?
When retrieving a directory from disk, using the following code
var directoryPath = new DirectoryPath("./"); (or new DirectoryPath(@".\"))
var directory = context.FileSystem.GetDirectory(directoryPath);

the following error is thrown:
Error: System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at Cake.Core.IO.Directory..ctor(DirectoryPath path)
   at Cake.Core.IO.FileSystem.GetDirectory(DirectoryPath path)

### What is Expected?
The retrieval of the directory from disk.

### What version of Cake are you using?
I've seen this error occur on 0.29 and 0.33

### Are you running on a 32 or 64 bit system?
We are running a 64-bit system.

### What environment are you running on?  Windows? Linux? Mac?
We are running on Windows.

### Are you running on a CI Server?  If so, which one?
The issue occurs both on our build server (TeamCity), as well as on our local machines.

**Comment by Meertman** [comment]
Created a gist containing a unit-test (using NUnit) that can be used to test for the issue:
https://gist.github.com/Meertman/ef6461c2adee967117f6500811bbe697
