### ISSUE TITLE
Error: Gulp Runner: Could not locate executable.

### ISSUE THREAD

**Issue by jitesh88** [cake-build/cake#2706]
### What You Are Seeing?
Error: Cake.Core.CakeException: Gulp Runner: Could not locate executable.

### What is Expected?
Gulp to work on the required task

### What version of Cake are you using?
0.21.1

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
bamboo

### How Did You Get This To Happen? (Steps to Reproduce)
#tool "nuget:?package=NUnit.ConsoleRunner&version=3.9.0"
#tool "nuget:?package=OpenCover&version=4.6.519"
#tool "nuget:?package=ReportGenerator&version=4.0.11"
#addin "Cake.FileHelpers&version=1.0.4"
#addin "Cake.XdtTransform&version=0.11.0"
#addin "Cake.Gulp&version=0.7.1"
#addin "Cake.Npm&version=0.11.0"
Task("Restore-NuGet-Packages")
    .Does(() =>
    {
		NuGetRestore(_solutionPath);
    });

Task("NpmInstall")
    .Does(() =>
    {
        NpmInstall(settings => settings.FromPath(_hostPath));
    });
	
Task("Gulp")
	.IsDependentOn("NpmInstall")
	.Does(() => 
	{
		Gulp.Global.Execute(settings => settings.WithGulpFile(_gulpFile).WithArguments("build-app"));
		Gulp.Global.Execute(settings => settings.WithGulpFile(_gulpFile).WithArguments("build-less"));
	});
	

### Output Log
========================================
Gulp
========================================
Executing task: Gulp
An error occurred when executing task 'Gulp'.
Error: Cake.Core.CakeException: Gulp Runner: Could not locate executable.
   at Cake.Core.Tooling.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Gulp.GulpGlobalRunner.Execute(Action`1 configure)
   at Submission#0.<.ctor>b__11()
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()

GIST LINK - Please create a gist and link to that gist here

OR

~~~sh
PLACE LOG CONTENT HERE
~~~

**Comment by gep13** [comment]
@jitesh88 do you have gulp installed globally on the machine that you are executing this script from?  If not, then I don't think it is going to work.

**Comment by jitesh88** [comment]
yes ive tried installing it globally and also locally

i ran npm install -g gulp and npm install gulp

still no luck.

**Comment by pascalberger** [comment]
@jitesh88 You'll need to install the gulp command line utility:

```
npm install --global gulp-cli
```
