### ISSUE TITLE
Input string not in correct format starting in v0.38.0

### ISSUE THREAD

**Issue by shaneray** [cake-build/cake#2798]
### What You Are Seeing?
"Input string was not in a correct format." error when powershell script contatains {

### What is Expected?
No error when curly brace is used.

### What version of Cake are you using?
v0.38.0 and greater

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
Local on PC and Jenkins

### How Did You Get This To Happen? (Steps to Reproduce)
use cake.powershell to execute a script with the following text "if ($LASTEXITCODE -gt 0) { throw \"script failed with exit code $LASTEXITCODE\" }"

### Output Log
```Error: System.AggregateException: One or more errors occurred. ---> System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.IO.TextWriter.Write(String format, Object[] arg)
   at System.IO.TextWriter.SyncTextWriter.Write(String format, Object[] arg)
   at System.Console.Write(String format, Object[] arg)
   at Cake.Core.CakeConsole.Write(String format, Object[] arg)
   at Cake.Core.Diagnostics.AnsiConsoleRenderer.Render(LogLevel level, String format, Object[] args)
   at Cake.Core.Diagnostics.CakeBuildLog.Write(Verbosity verbosity, LogLevel level, String format, Object[] args)
   at Cake.Powershell.PowershellRunner.LogExecutingCommand(PowershellSettings settings, String script, Boolean safe)
   at Cake.Powershell.PowershellRunner.Start(String script, PowershellSettings settings)
   at Submission#0.StartPowershellScript(String script, PowershellSettings settings) in :line 3231
   at Submission#0.BuildRevIoMigrationTemplate() in C:\workspace\git\Lingo\Core Services\lingo.pivot.web\build.cake:line 147
   at Submission#0.<<Initialize>>b__0_22() in C:\workspace\git\Lingo\Core Services\lingo.pivot.web\build.cake:line 83
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass32_0.<Does>b__0(ICakeContext x)
   at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTask>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<<Initialize>>d__0.MoveNext() in C:\workspace\git\Lingo\Core Services\lingo.pivot.web\build.cake:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
---> (Inner Exception #0) System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.IO.TextWriter.Write(String format, Object[] arg)
   at System.IO.TextWriter.SyncTextWriter.Write(String format, Object[] arg)
   at System.Console.Write(String format, Object[] arg)
   at Cake.Core.CakeConsole.Write(String format, Object[] arg)
   at Cake.Core.Diagnostics.AnsiConsoleRenderer.Render(LogLevel level, String format, Object[] args)
   at Cake.Core.Diagnostics.CakeBuildLog.Write(Verbosity verbosity, LogLevel level, String format, Object[] args)
   at Cake.Powershell.PowershellRunner.LogExecutingCommand(PowershellSettings settings, String script, Boolean safe)
   at Cake.Powershell.PowershellRunner.Start(String script, PowershellSettings settings)
   at Submission#0.StartPowershellScript(String script, PowershellSettings settings) in :line 3231
   at Submission#0.BuildRevIoMigrationTemplate() in C:\workspace\git\Lingo\Core Services\lingo.pivot.web\build.cake:line 147
   at Submission#0.<<Initialize>>b__0_22() in C:\workspace\git\Lingo\Core Services\lingo.pivot.web\build.cake:line 83
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass32_0.<Does>b__0(ICakeContext x)
   at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)                       at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()                                                  --- End of stack trace from previous location where exception was thrown ---                                               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()                                                       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)                       at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()                                                           --- End of stack trace from previous location where exception was thrown ---                                               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTask>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<<Initialize>>d__0.MoveNext() in C:\workspace\git\Lingo\Core Services\lingo.pivot.web\build.cake:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()<---
```

**Comment by devlead** [comment]
Confirmed change in behavior, minimal repro
```cake
static string EscapeCurleyBrackets(this string message)
{
    return message.Replace("{", "{{").Replace("}", "}}");
}

Context.Log.Debug(
    Verbosity.Normal,
    string.Format("Executing: {0}", "if ($LASTEXITCODE -gt 0) { throw \"script failed with exit code $LASTEXITCODE\" }".EscapeCurleyBrackets())
    );
```

Output 0.37.0
![image](https://user-images.githubusercontent.com/1647294/84389882-0822ed80-abf7-11ea-86d8-a12e8362be3c.png)

Output 0.38.x
![image](https://user-images.githubusercontent.com/1647294/84389948-24bf2580-abf7-11ea-8c4f-b43bbd7292f6.png)

Output 0.38.x on terminal that doesn't support ANSI 
![image](https://user-images.githubusercontent.com/1647294/84390011-3f919a00-abf7-11ea-8d73-2e5d731149c8.png)

Input string to `Context.Log.Debug`
`Executing: if ($LASTEXITCODE -gt 0) {{ throw "script failed with exit code $LASTEXITCODE" }}`

**Comment by devlead** [comment]
Think I see an issue in the tokenization, if lead right and I find the time, then I'll propose a PR.
