### ISSUE TITLE
Resolved tool path for "docker" should be the linux version of docker when running under WSL

### ISSUE THREAD

**Issue by mabead** [cake-build/cake#2843]
### What You Are Seeing?

I am running a cake script under wsl 2. When the `DockerRun` function is invoked, it uses the `docker.exe` in my windows env instead of the `docker` in my linux distribution, thus resulting in errors when mounting volumes. Ex:

```
========================================
Default
========================================
Executing task: Default
Resolved tool to path /mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe
Executing: /mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe run --entrypoint "sh" --rm --volume "/tmp/docker_vs_cake_in_wsl:/repo" gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1 -c "./dotnet-gitversion /repo /output buildserver"
Cannot find the .git directory
INFO [08/28/20 20:24:13:47] Working directory: /repo
INFO [08/28/20 20:24:13:52] Done writing
```

### What is Expected?

The resolved tool path should be `/usr/bin/docker` instead of `/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe`.

Note that when I type the command `docker run --entrypoint "sh" --rm --volume "/tmp/docker_vs_cake_in_wsl:/repo" gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1 -c "./dotnet-gitversion /repo"`, it works as expected.

### What version of Cake are you using?

```
mbeaudry@MG-COMP-0148:/tmp/docker_vs_cake_in_wsl$ dotnet-cake --version
0.38.4
```

### Are you running on a 32 or 64 bit system?

64 bits

### What environment are you running on?  Windows? Linux? Mac?

WSL 2 (ubuntu distro)

### Are you running on a CI Server?  If so, which one?

No

### How Did You Get This To Happen? (Steps to Reproduce)

Here's a simple cake script that shows the problem:
```csharp
#addin "Cake.Docker"

Task("Default")
    .Does(() => {
        
        var dockerRunSettings = new DockerContainerRunSettings()
        {
            Rm = true, // delete container after run
            Volume = new string[]{ MakeAbsolute(Directory(".")) +":/repo"  }, // mount the current root git folder into /repo
            Entrypoint = "sh"
        };
        
        DockerRun(dockerRunSettings,
            "gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1",
            "-c",
            "\"./dotnet-gitversion /repo /output buildserver\"");
    });


RunTarget(Argument("target", "Default"));
```

Then simply run it with `dotnet-cake --verbosity=diagnostic`. Note that a `git init` may be required to have the script work correctly.

### Output Log
~~~sh
========================================
Default
========================================
Executing task: Default
Resolved tool to path /mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe
Executing: /mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe run --entrypoint "sh" --rm --volume "/tmp/docker_vs_cake_in_wsl:/repo" gittools/gitversion:5.3.5-linux-alpine.3.10-x64-netcoreapp3.1 -c "./dotnet-gitversion /repo /output buildserver"
Cannot find the .git directory
INFO [08/28/20 20:24:13:47] Working directory: /repo
INFO [08/28/20 20:24:13:52] Done writing
An error occurred when executing task 'Default'.
Error: System.AggregateException: One or more errors occurred. (Docker: Process returned an error (exit code 1).)
 ---> Cake.Core.CakeException: Docker: Process returned an error (exit code 1).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 136
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 121
   at Cake.Docker.GenericDockerRunner`1.RunWithResult[T](String command, TSettings settings, Func`2 processOutput, String[] arguments) in D:\GitProjects\Righthand\Cake\Cake.Docker\src\Cake.Docker\GenericDockerRunner.cs:line 107
   at Cake.Docker.DockerAliases.DockerRun(ICakeContext context, DockerContainerRunSettings settings, String image, String command, String[] args) in D:\GitProjects\Righthand\Cake\Cake.Docker\src\Cake.Docker\Container\Run\Docker.Aliases.Run.cs:line 59
   at Submission#0.DockerRun(DockerContainerRunSettings settings, String image, String command, String[] args) in :line 3255
   at Submission#0.<<Initialize>>b__0_0() in /tmp/docker_vs_cake_in_wsl/build.cake:line 13
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass29_0.<Does>b__0(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 26
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass32_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 83
   at Cake.Core.CakeTask.Execute(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTask.cs:line 125
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context) in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 87
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 336
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 361
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 369
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 284
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 247
   at Cake.Scripting.BuildScriptHost.RunTargetAsync(String target) in C:\projects\cake\src\Cake\Scripting\BuildScriptHost.cs:line 47
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 191
   at Submission#0.<<Initialize>>d__0.MoveNext() in /tmp/docker_vs_cake_in_wsl/build.cake:line 20
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Scripting\Roslyn\RoslynScriptSession.cs:line 136
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 219
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 81
~~~

**Comment by pascalberger** [comment]
The `DockerRun` alias is not part of Cake but from the Cake.Docker addin. You should open an issue at https://github.com/MihaMarkic/Cake.Docker/

/cc @MihaMarkic

**Comment by mabead** [comment]
Moved to https://github.com/MihaMarkic/Cake.Docker/issues/78.
