### ISSUE TITLE
Trying to Run DotNetCoreTest using Nunit results in an error when test fails

### ISSUE THREAD

**Issue by suegy** [cake-build/cake#2855]
### What You Are Seeing?
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  X Test1 [38ms]
  Stack Trace:
     at Exercise.Tests.Tests.Test1() in E:\[folder]\test\Exercise.Tests\UnitTest1.cs:line 20

Test Run Failed.
Total tests: 1
     Failed: 1
 Total time: 1.0561 Seconds
An error occurred when executing task 'Tests'.
Error: System.AggregateException: One or more errors occurred. (.NET Core CLI: Process returned an error (exit code 1).)
 ---> Cake.Core.CakeException: .NET Core CLI: Process returned an error (exit code 1).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 136
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 121
   at Cake.Common.Tools.DotNetCore.DotNetCoreTool`1.RunCommand(TSettings settings, ProcessArgumentBuilder arguments) in C:\projects\cake\src\Cake.Common\Tools\DotNetCore\DotNetCoreTool.cs:line 64
   at Cake.Common.Tools.DotNetCore.Test.DotNetCoreTester.Test(String project, DotNetCoreTestSettings settings) in C:\projects\cake\src\Cake.Common\Tools\DotNetCore\Test\DotNetCoreTester.cs:line 48
   at Cake.Common.Tools.DotNetCore.DotNetCoreAliases.DotNetCoreTest(ICakeContext context, String project, DotNetCoreTestSettings settings) in C:\projects\cake\src\Cake.Common\Tools\DotNetCore\DotNetCoreAliases.cs:line 589
   at Cake.Common.Tools.DotNetCore.DotNetCoreAliases.DotNetCoreTest(ICakeContext context, String project) in C:\projects\cake\src\Cake.Common\Tools\DotNetCore\DotNetCoreAliases.cs:line 527
   at Submission#0.DotNetCoreTest(String project) in :line 926
   at Submission#0.<<Initialize>>b__0_3() in E:\[folder]\test\build.cake:line 34
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass29_0.<Does>b__0(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 26
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass32_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 83
   at Cake.Core.CakeTask.Execute(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTask.cs:line 125
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context) in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 87
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 336
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 361
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 369
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 284
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 247
   at Cake.Scripting.BuildScriptHost.RunTargetAsync(String target) in C:\projects\cake\src\Cake\Scripting\BuildScriptHost.cs:line 47
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 191
   at Submission#0.<<Initialize>>d__0.MoveNext() in E:\[folder]\test\build.cake:line 44
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Scripting\Roslyn\RoslynScriptSession.cs:line 136
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 219
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 81
### What is Expected?
The test to simply fail without an error being shown
### What version of Cake are you using?
0.38.4
### Are you running on a 32 or 64 bit system?
64
### What environment are you running on?  Windows? Linux? Mac?
Windows10
### Are you running on a CI Server?  If so, which one?
no

### How Did You Get This To Happen? (Steps to Reproduce)
dotnet new tool-manifest
dotnet tool install Cake.Tool --version=0.38.4
dotnet new console -o <Name>
mkdir <Name>.Tests
cd <Name>.Tests
dotnet new nunit
dotnot add ../<Name>/<Name>.csproj
then adding #tool nunit runner to build.cake 
setting a test task using DotNetCoreTest

### Output Log
 dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mholo65** [comment]
> Test Run Failed.
Total tests: 1
Failed: 1
Total time: 1.0561 Seconds

The test is failing, which will cause NUnit runner to return non-zero exit code, which will cause Cake to throw an exception. This is expected behavior.

Depending on what kind of behavior you want, please take a look at [Error handling](https://cakebuild.net/docs/fundamentals/error-handling) or just wrap the NUnit call in a `try...catch`.

Closing this.
