### ISSUE TITLE
Tool resolving in Frosting tasks

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#3038]
### What You Are Seeing?
I can restore a .NET Tool using the Cake.DotNet.Module and then call it in the build context constructor. But when calling the same tool in the Setup or a task an error is thrown:

```
Error: GitVersion: Could not locate executable.
```

### What is Expected?
It should be possible to call .NET Tools also from setup or tasks.

### What version of Cake are you using?
1.0.0-rc0002

### Are you running on a 32 or 64 bit system?
64-Bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)

1. Create a new Froasting project and setup the host like this:

   ```
   return new CakeHost()
       .UseContext<BuildContext>()
       .UseModule<DotNetToolModule>()
       .UseTool(new Uri("dotnet:?package=GitVersion.Tool&version=5.6.3"))
       .Run(args);
   ```
2. Call `context.GitVersion();` in the constructor of the `BuildContext` class
3. Call `context.GitVersion();` in a task

**Comment by pascalberger** [comment]
This is caused by working directory and probably a duplicate of https://github.com/cake-build/cake/issues/2904

**Comment by patriksvensson** [comment]
@pascalberger Can't reproduce. I'm closing the issue.

![image](https://user-images.githubusercontent.com/357872/105614185-13aed780-5dc8-11eb-80c0-7867f4176ea2.png)

**Comment by pascalberger** [comment]
I'll add a repro repository later

**Comment by pascalberger** [comment]
Here's a repository where it can be reproduced: https://github.com/pascalberger/cake-gh-3038

For the reproduction to work it is important that GitVersion is not available on the system (e.g. installed as .NET global tool or through Chocolatey). In this case the behavior can still be seen when running with diagnostic verbosity where it is visible that global instance is called when running from a task instead of the version installed in the build script (see this GitHub actions run: https://github.com/pascalberger/cake-gh-3038/runs/1758010781?check_suite_focus=true#step:5:36).

**Comment by augustoproiete** [comment]
> Here's a repository where it can be reproduced: https://github.com/pascalberger/cake-gh-3038

I can repro on my machine:

```
.\build.ps1 --verbosity=diagnostic
Tool GitVersion.Tool is already installed, with required version.
Building version 0.1.0...
Registering task: Default

========================================
Default
========================================
Executing task: Default
Could not resolve path for tool "GitVersion.exe" using these directories: C:/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.4.3243.0_x64__8wekyb3d8bbwe,C:/WINDOWS/system32,C:/WINDOWS,C:/WINDOWS/System32/Wbem,C:/WINDOWS/System32/WindowsPowerShell/v1.0,C:/WINDOWS/System32/OpenSSH,C:/Program Files/PuTTY,C:/Program Files/dotnet,C:/Program Files/Microsoft SQL Server/130/Tools/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn,C:/Program Files/Microsoft SQL Server/140/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn,C:/Program Files/Microsoft SQL Server/140/DTS/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn,C:/Program Files (x86)/Yarn/bin,C:/Program Files/Seq,C:/Program Files/Seq/Client,C:/Users/cproiete/AppData/Roaming/nvm,C:/Program Files/nodejs,C:/Program Files/Amazon/AWSCLI/bin,C:/ProgramData/chocolatey/bin,C:/Program Files/LINQPad6,C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL,C:/Program Files/Intel/Intel(R) Management Engine Components/DAL,C:/Program Files/Amazon/AWSSAMCLI/bin,C:/Program Files/Docker/Docker/resources/bin,C:/ProgramData/DockerDesktop/version-bin,C:/Program Files/Azure Data Studio/bin,C:/Program Files/Git/cmd,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/HostX86/x86,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/VC/VCPackages,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/bin/Roslyn,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Team Tools/Performance Tools,C:/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/vs2019,C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools,C:/Program Files (x86)/HTML Help Workshop,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/FSharp,C:/Program Files (x86)/Windows Kits/10/bin/10.0.18362.0/x86,C:/Program Files (x86)/Windows Kits/10/bin/x86,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community//MSBuild/Current/Bin,C:/Windows/Microsoft.NET/Framework/v4.0.30319,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools,C:/ProgramData/DockerDesktop/version-bin,C:/Program Files/Docker/Docker/Resources/bin,C:/WINDOWS/system32,C:/WINDOWS,C:/WINDOWS/System32/Wbem,C:/WINDOWS/System32/WindowsPowerShell/v1.0,C:/WINDOWS/System32/OpenSSH,C:/Program Files/PuTTY,C:/Program Files/dotnet,C:/Program Files/Microsoft SQL Server/130/Tools/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn,C:/Program Files/Microsoft SQL Server/140/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn,C:/Program Files/Microsoft SQL Server/140/DTS/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn,C:/Program Files (x86)/Yarn/bin,C:/Program Files/Seq,C:/Program Files/Seq/Client,C:/Users/cproiete/AppData/Roaming/nvm,C:/Program Files/nodejs,C:/Program Files/Amazon/AWSCLI/bin,C:/Program Files/Amazon/AWSSAMCLI/bin,C:/ProgramData/chocolatey/bin,C:/Program Files/LINQPad6,C:/Program Files/Git/cmd,C:/Users/cproiete/.cargo/bin,C:/Users/cproiete/AppData/Local/Programs/Python/Python37/Scripts,C:/Users/cproiete/AppData/Local/Programs/Python/Python37,C:/Users/cproiete/AppData/Local/Julia-1.3.0/bin,C:/Users/cproiete/AppData/Local/Microsoft/WindowsApps,C:/Users/cproiete/AppData/Local/Programs/Microsoft VS Code/bin,C:/Users/cproiete/AppData/Roaming/npm,C:/Users/cproiete/AppData/Local/Yarn/bin,C:/Users/cproiete/.dotnet/tools,C:/Users/cproiete/AppData/roaming/Python/Python37/scripts,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja,C:/Program Files (x86)/Rico Suter/NSwagStudio,C:/Users/cproiete/AppData/Local/Microsoft/WindowsApps,C:/Program Files (x86)/GitHub CLI,C:/Users/cproiete/.dotnet/tools,C:/Program Files/Azure Data Studio/bin,C:/Users/cproiete/.dotnet/tools,C:/Users/cproiete/.dotnet/tools
Could not resolve path for tool "dotnet-gitversion" using these directories: C:/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.4.3243.0_x64__8wekyb3d8bbwe,C:/WINDOWS/system32,C:/WINDOWS,C:/WINDOWS/System32/Wbem,C:/WINDOWS/System32/WindowsPowerShell/v1.0,C:/WINDOWS/System32/OpenSSH,C:/Program Files/PuTTY,C:/Program Files/dotnet,C:/Program Files/Microsoft SQL Server/130/Tools/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn,C:/Program Files/Microsoft SQL Server/140/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn,C:/Program Files/Microsoft SQL Server/140/DTS/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn,C:/Program Files (x86)/Yarn/bin,C:/Program Files/Seq,C:/Program Files/Seq/Client,C:/Users/cproiete/AppData/Roaming/nvm,C:/Program Files/nodejs,C:/Program Files/Amazon/AWSCLI/bin,C:/ProgramData/chocolatey/bin,C:/Program Files/LINQPad6,C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL,C:/Program Files/Intel/Intel(R) Management Engine Components/DAL,C:/Program Files/Amazon/AWSSAMCLI/bin,C:/Program Files/Docker/Docker/resources/bin,C:/ProgramData/DockerDesktop/version-bin,C:/Program Files/Azure Data Studio/bin,C:/Program Files/Git/cmd,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/HostX86/x86,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/VC/VCPackages,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/bin/Roslyn,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Team Tools/Performance Tools,C:/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/vs2019,C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools,C:/Program Files (x86)/HTML Help Workshop,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/FSharp,C:/Program Files (x86)/Windows Kits/10/bin/10.0.18362.0/x86,C:/Program Files (x86)/Windows Kits/10/bin/x86,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community//MSBuild/Current/Bin,C:/Windows/Microsoft.NET/Framework/v4.0.30319,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools,C:/ProgramData/DockerDesktop/version-bin,C:/Program Files/Docker/Docker/Resources/bin,C:/WINDOWS/system32,C:/WINDOWS,C:/WINDOWS/System32/Wbem,C:/WINDOWS/System32/WindowsPowerShell/v1.0,C:/WINDOWS/System32/OpenSSH,C:/Program Files/PuTTY,C:/Program Files/dotnet,C:/Program Files/Microsoft SQL Server/130/Tools/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn,C:/Program Files/Microsoft SQL Server/140/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn,C:/Program Files/Microsoft SQL Server/140/DTS/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn,C:/Program Files (x86)/Yarn/bin,C:/Program Files/Seq,C:/Program Files/Seq/Client,C:/Users/cproiete/AppData/Roaming/nvm,C:/Program Files/nodejs,C:/Program Files/Amazon/AWSCLI/bin,C:/Program Files/Amazon/AWSSAMCLI/bin,C:/ProgramData/chocolatey/bin,C:/Program Files/LINQPad6,C:/Program Files/Git/cmd,C:/Users/cproiete/.cargo/bin,C:/Users/cproiete/AppData/Local/Programs/Python/Python37/Scripts,C:/Users/cproiete/AppData/Local/Programs/Python/Python37,C:/Users/cproiete/AppData/Local/Julia-1.3.0/bin,C:/Users/cproiete/AppData/Local/Microsoft/WindowsApps,C:/Users/cproiete/AppData/Local/Programs/Microsoft VS Code/bin,C:/Users/cproiete/AppData/Roaming/npm,C:/Users/cproiete/AppData/Local/Yarn/bin,C:/Users/cproiete/.dotnet/tools,C:/Users/cproiete/AppData/roaming/Python/Python37/scripts,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja,C:/Program Files (x86)/Rico Suter/NSwagStudio,C:/Users/cproiete/AppData/Local/Microsoft/WindowsApps,C:/Program Files (x86)/GitHub CLI,C:/Users/cproiete/.dotnet/tools,C:/Program Files/Azure Data Studio/bin,C:/Users/cproiete/.dotnet/tools,C:/Users/cproiete/.dotnet/tools
Could not resolve path for tool "dotnet-gitversion.exe" using these directories: C:/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.4.3243.0_x64__8wekyb3d8bbwe,C:/WINDOWS/system32,C:/WINDOWS,C:/WINDOWS/System32/Wbem,C:/WINDOWS/System32/WindowsPowerShell/v1.0,C:/WINDOWS/System32/OpenSSH,C:/Program Files/PuTTY,C:/Program Files/dotnet,C:/Program Files/Microsoft SQL Server/130/Tools/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn,C:/Program Files/Microsoft SQL Server/140/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn,C:/Program Files/Microsoft SQL Server/140/DTS/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn,C:/Program Files (x86)/Yarn/bin,C:/Program Files/Seq,C:/Program Files/Seq/Client,C:/Users/cproiete/AppData/Roaming/nvm,C:/Program Files/nodejs,C:/Program Files/Amazon/AWSCLI/bin,C:/ProgramData/chocolatey/bin,C:/Program Files/LINQPad6,C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL,C:/Program Files/Intel/Intel(R) Management Engine Components/DAL,C:/Program Files/Amazon/AWSSAMCLI/bin,C:/Program Files/Docker/Docker/resources/bin,C:/ProgramData/DockerDesktop/version-bin,C:/Program Files/Azure Data Studio/bin,C:/Program Files/Git/cmd,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/HostX86/x86,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/VC/VCPackages,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/bin/Roslyn,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Team Tools/Performance Tools,C:/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/vs2019,C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools,C:/Program Files (x86)/HTML Help Workshop,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/FSharp,C:/Program Files (x86)/Windows Kits/10/bin/10.0.18362.0/x86,C:/Program Files (x86)/Windows Kits/10/bin/x86,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community//MSBuild/Current/Bin,C:/Windows/Microsoft.NET/Framework/v4.0.30319,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools,C:/ProgramData/DockerDesktop/version-bin,C:/Program Files/Docker/Docker/Resources/bin,C:/WINDOWS/system32,C:/WINDOWS,C:/WINDOWS/System32/Wbem,C:/WINDOWS/System32/WindowsPowerShell/v1.0,C:/WINDOWS/System32/OpenSSH,C:/Program Files/PuTTY,C:/Program Files/dotnet,C:/Program Files/Microsoft SQL Server/130/Tools/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn,C:/Program Files/Microsoft SQL Server/140/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn,C:/Program Files/Microsoft SQL Server/140/DTS/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn,C:/Program Files (x86)/Yarn/bin,C:/Program Files/Seq,C:/Program Files/Seq/Client,C:/Users/cproiete/AppData/Roaming/nvm,C:/Program Files/nodejs,C:/Program Files/Amazon/AWSCLI/bin,C:/Program Files/Amazon/AWSSAMCLI/bin,C:/ProgramData/chocolatey/bin,C:/Program Files/LINQPad6,C:/Program Files/Git/cmd,C:/Users/cproiete/.cargo/bin,C:/Users/cproiete/AppData/Local/Programs/Python/Python37/Scripts,C:/Users/cproiete/AppData/Local/Programs/Python/Python37,C:/Users/cproiete/AppData/Local/Julia-1.3.0/bin,C:/Users/cproiete/AppData/Local/Microsoft/WindowsApps,C:/Users/cproiete/AppData/Local/Programs/Microsoft VS Code/bin,C:/Users/cproiete/AppData/Roaming/npm,C:/Users/cproiete/AppData/Local/Yarn/bin,C:/Users/cproiete/.dotnet/tools,C:/Users/cproiete/AppData/roaming/Python/Python37/scripts,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin,C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja,C:/Program Files (x86)/Rico Suter/NSwagStudio,C:/Users/cproiete/AppData/Local/Microsoft/WindowsApps,C:/Program Files (x86)/GitHub CLI,C:/Users/cproiete/.dotnet/tools,C:/Program Files/Azure Data Studio/bin,C:/Users/cproiete/.dotnet/tools,C:/Users/cproiete/.dotnet/tools
An error occurred when executing task 'Default'.
Error: Cake.Core.CakeException: GitVersion: Could not locate executable.
   at Cake.Core.Tooling.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Common.Tools.GitVersion.GitVersionRunner.Run(GitVersionSettings settings)
   at Cake.Common.Tools.GitVersion.GitVersionAliases.GitVersion(ICakeContext context, GitVersionSettings settings)
   at Cake.Common.Tools.GitVersion.GitVersionAliases.GitVersion(ICakeContext context)
   at DefaultTask.Run(ICakeContext context) in C:\augustoproiete\oss\cap\forks\cake-build--\zzz_repro_pascalberger--cake-gh-3038\build\Tasks\DefaultTask.cs:line 13
   at Cake.Frosting.FrostingTask`1.Cake.Frosting.IFrostingTask.RunAsync(ICakeContext context)
   at Cake.Core.CakeTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report)
```

**Comment by pascalberger** [comment]
Error is triggered by [setting working directory](https://github.com/pascalberger/cake-gh-3038/blob/master/build/Program.cs#L12) and might be fixed with https://github.com/cake-build/cake/pull/3048.

**Comment by pascalberger** [comment]
Fixed with https://github.com/cake-build/cake/pull/3048
