### ISSUE TITLE
Reference preprocessor directive does not support @ verbatim identifier

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3053]
The following usage of the [reference preprocessor directive](https://cakebuild.net/docs/writing-builds/preprocessor-directives#reference-directive) fails with an `ArgumentNullException` even though the `string` is valid C#:

```
#r @"C:\MyProject\MyAssembly.dll"
```

```
Error: System.ArgumentNullException: Value cannot be null. (Parameter 'references[25]')
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.AddRangeChecked[T](ArrayBuilder`1 builder, IEnumerable`1 items, String parameterName)
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.ConcatChecked[T](ImmutableArray`1 existing, IEnumerable`1 items, String parameterName)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.AddReferences(IEnumerable`1 references)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.AddReferences(IEnumerable`1 references)
   at Cake.Infrastructure.Scripting.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Infrastructure\Scripting\RoslynScriptSession.cs:line 94
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 172
   at Cake.Features.Building.BuildFeature.RunCore(IRemainingArguments arguments, BuildFeatureSettings settings) in C:\projects\cake\src\Cake\Features\Building\BuildFeature.cs:line 99
   at Cake.Features.Building.BuildFeature.Run(IRemainingArguments arguments, BuildFeatureSettings settings) in C:\projects\cake\src\Cake\Features\Building\BuildFeature.cs:line 49
   at Cake.Commands.DefaultCommand.Execute(CommandContext context, DefaultCommandSettings settings) in C:\projects\cake\src\Cake\Commands\DefaultCommand.cs:line 72
````

However, without the `@` verbatim identifier, it works even though it's not really a valid C# `string`:

```
#r "C:\MyProject\MyAssembly.dll"
```

---

Cake version: 1.0.0-rc0002 (Cake.Tool)

**Comment by devlead** [comment]
Preprocessor directives are processed before the C# compiler kicks in, and any Cake specific and `#using` directives are removed before code gets compiled. Don't think we would want to write our own C# compiler to support all variants of strings C# can have. Maybe just document what's supported.

**Comment by augustoproiete** [comment]
The main issue (for me) is fixing the problem I stated in the title: `Reference preprocessor directive does not support @ verbatim identifier`

```
#r @"C:\MyProject\MyAssembly.dll"
```

Is valid C# and should work fine... The user shouldn't get a cryptic error IMO.

**Comment by devlead** [comment]
No `#r` isn't part of the C# spec, it's part of most C# scripting implementations though, including `csi.exe`

We should probably throw a better error, but don't think we should implement full C# string support, don't believe even [C# preprocessor](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/) evaluates standard C# string expressions.

This is what `csi.exe` reports

`#r "C:\MyProject\MyAssembly.dll"`
no error
`#r @"C:\MyProject\MyAssembly.dll"`

will report

```diff
- (1,4): error CS7010: Quoted file name expected
```

if we add any validation we need to make sure all existing use cases work i.e. GAC assemblies still work which can be referenced by name without extension.

**Comment by augustoproiete** [comment]
Interesting. I'd be happier with that CS7010 error message for sure. It took me a while to figure out the `@` the problem.

**Comment by augustoproiete** [comment]
Closing as `wont-fix`
