### ISSUE TITLE
PathTooLongException in Globber

### ISSUE THREAD

**Issue by marcosnz** [cake-build/cake#307]
We have a node/grunt module that produces some very long directory structures e.g.

```
C:\Repositories\GivealittleV4\src\Assets\Web\node_modules\grunt-contrib-compass\node_modules\bin-version-check\node_modules\bin-version\node_modules\find-versions\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_modules\is-finite\node_modules\number-is-nan
```
Note that when accessed via explorer it reverts to 8.3 format:
```
C:\REPOSI~2\GIVEAL~2\Src\Assets\Web\NODE_M~1\GRUNT-~4\NODE_M~1\BIN-VE~1\NODE_M~1\BIN-VE~1\NODE_M~1\FIND-V~1\NODE_M~1\meow\NODE_M~1\INDENT~1\NODE_M~1\REPEAT~1\NODE_M~1\IS-FIN~1\node_modules\number-is-nan 
```
I have a simple globber expression to find csproj files:
```CSharp
List<FilePath> projects = GetFiles("./src/**/*.csproj").ToList();
```
But produces an error because of the long path:
```
Error: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.IO.FileSystemInfo.get_FullName()
   at Cake.Core.IO.Directory.<GetDirectories>b__0(DirectoryInfo directory)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Walk(DirectoryPath rootPath, Stack`1 segments, Func`2 predicate)
   at Cake.Core.IO.Globber.Match(String pattern, Func`2 predicate)
   at Cake.Common.IO.GlobbingAliases.GetFiles(ICakeContext context, String pattern)
   at Submission#0.GetFiles(String pattern)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(IEnumerable`1 args)
```

**Comment by devlead** [comment]
Probably the work started with #261 will address this, meanwhile an hack is to supply a filter predicate to exclude the node module folder, unless that I the on you want to take action on.

**Comment by devlead** [comment]
[Here](http://cakebuild.net/api/cake.common.io/b6f866f7/62db42f4) you can see an sample of filtering out the node modules folder.

**Comment by marcosnz** [comment]
Thanks! I'll close this as there is a  workround amd it  will be covered by #261
