### ISSUE TITLE
Attribute `[IsDependeeOf]` doesn't work

### ISSUE THREAD

**Issue by VSerykh** [cake-build/cake#3072]
### What You Are Seeing?

When I create a `FrostingTask` with `[IsDependeeOf()]`, it doesn't work.

The error message is:

```
Error: Task 'World' has specified that it's a dependency for task 'IsDependeeOfAttribute' which does not exist.
```

### What is Expected?

It's expected not to fail and run a task with a reversed dependency.

### What version of Cake are you using?

Probably `v1.0.0-rc0003`.

I tested the latest code from `release/1.0.0`.

### Are you running on a 32- or 64-bit system?

64-bit

### What environment are you running on?  Windows? Linux? Mac?

Windows 10

### Are you running on a CI Server?  If so, which one?

No.

### How Did You Get This To Happen? (Steps to Reproduce)

Simply put valid `[IsDependeeOf()]` on any task.

### Output Log
~~~cmd
NuGet Config not specified. Will use NuGet default mechanism for resolving it.
Registering task: Hello
Registering task: World
Registering task: Default
Error: Cake.Core.CakeException: Task 'World' has specified that it's a dependency for task 'IsDependeeOfAttribute' which does not exist.
   at Cake.Core.Graph.CakeGraphBuilder.Build(IReadOnlyCollection`1 tasks)
   at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Cake.Cli.BuildScriptHost`1.<RunTargetAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Cake.Frosting.Internal.FrostingEngine`1.Run(String target)
   at Cake.Frosting.Internal.DefaultCommand.Execute(CommandContext context, DefaultCommandSettings settings)
~~~

**Comment by patriksvensson** [comment]
@VSerykh Could you post the whole build pipeline here as well?

**Comment by pascalberger** [comment]
Fixed with https://github.com/cake-build/cake/pull/3071
