### ISSUE TITLE
ParseSolution throws IndexOutOfRangeException on empty lines

### ISSUE THREAD

**Issue by nmbro** [cake-build/cake#3143]
### What You Are Seeing?
`ParseSolution(ICakeContext context, FilePath solutionPath)` doesn't handle empty lines in the solution file correctly.

### What is Expected?
It's expected for it to just ignore the empty lines.

### What version of Cake are you using?
1.0.0

### Are you running on a 32 or 64 bit system?
64 bit, shouldn't matter

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
no

### How Did You Get This To Happen? (Steps to Reproduce)
Clone https://github.com/nmbro/cake-bug2
Run the `build.ps1`

The steps to reproduce is that the solution file has to have a blank line in the NestedProject section:

```
	GlobalSection(NestedProjects) = preSolution

		{59882916-5E07-4B05-91B2-C4449B095B78} = {2A10A5BE-0BDF-47BA-ADC2-33C669B1FDC2}
		{ED234CCE-59CC-442B-A059-C5742A191803} = {D7FA2608-3CBB-4C1B-A648-FEA180C64690}
	EndGlobalSection
```

This causes the `Cake.Common.Solution.SolutionAliases.ParseSolution(ICakeContext context, FilePath solutionPath)` to fail.

### Output Log
~~~sh
PS C:\dev\cake-bug2> .\build.ps1 -w C:\dev\cake-bug2\ -v Diagnostic
NuGet Config not specified. Will use NuGet default mechanism for resolving it.
Registering task: SolutionBug
Registering task: Default

========================================
SolutionBug
========================================
Executing task: SolutionBug
An error occurred when executing task 'SolutionBug'.
Error: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Cake.Common.Solution.SolutionParser.<>c__DisplayClass5_0.<ParseNestedProjectLine>b__0(SolutionProject x)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Cake.Common.Solution.SolutionParser.ParseNestedProjectLine(List`1 projects, String line)
   at Cake.Common.Solution.SolutionParser.Parse(FilePath solutionPath)
   at Cake.Common.Solution.SolutionAliases.ParseSolution(ICakeContext context, FilePath solutionPath)
   at SolutionTask.Run(BuildContext context) in C:\dev\cake-bug2\build\Program.cs:line 28
   at Cake.Frosting.FrostingTask`1.Cake.Frosting.IFrostingTask.RunAsync(ICakeContext context)
   at Cake.Core.CakeTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report)
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings)
   at Cake.Cli.BuildScriptHost`1.RunTargetAsync(String target)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Cake.Frosting.Internal.FrostingEngine`1.Run(String target)
   at Cake.Frosting.Internal.DefaultCommand.Execute(CommandContext context, DefaultCommandSettings settings)
~~~

**Comment by gep13** [comment]
@nmbro i am curious.... Does this happen with the same method in Cake.Incubator?

It has been a long term goal to bring the methods from Cake.Incubator into Cake properly.

**Comment by nmbro** [comment]
I can give it a shot
