### ISSUE TITLE
Unable to retrieve target argument with Frosting

### ISSUE THREAD

**Issue by nathangiuliani** [cake-build/cake#3291]
### What You Are Seeing?
Unable to retrieve the value passed to the `target` command line argument by using the Arguments method. - e.g. `context.Argument<string>("target")` throws an exception, running `context.HasArgument("target")` returns false even when a target argument is provided, and browsing the arguments object while in a live debug quite clearly shows they are not there.

Note that verbosity does not appear to be available any more also.

These both worked in 0.38.5, but stopped working at some point during 1.0.0 release candidates.

Have tested in a cake script with 1.1.0, and this still works as it did in 0.38.5 - this seems to be specific to Frosting.

Original discussion at https://github.com/cake-build/cake/discussions/3290

### What is Expected?
The value for the target argument to be returned.

### What version of Cake are you using?
1.1.0

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
n/a - occurs locally or in a pipeline

### How Did You Get This To Happen? (Steps to Reproduce)
See my example repository at https://github.com/nathangiuliani/cake-targettest-frosting. The first commit has everything working with 0.38.5, and the last has it updated to 1.1.0 to demonstrate the issue.

Ensure to execute with a target argument, e.g. `--target=Another`, to illustrate this issue the code throws an exception if no target argument is found. This will occur with 1.1.0 no matter what arguments are provided, but will work fine on 0.38.5.

### Output Log
```
NuGet Config not specified. Will use NuGet default mechanism for resolving it.
Registering task: Another
Registering task: Default
Registering setup: Lifetime
Registering teardown: Lifetime

----------------------------------------
Setup
----------------------------------------
Executing custom setup action...
Setting things up...

----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Tearing things down...
Error: System.ArgumentNullException: Target argument is not available
 ---> Cake.Core.CakeException: Argument 'target' was not set.
   at Cake.Common.ArgumentAliases.Argument[T](ICakeContext context, String name)
   at Lifetime.Setup(Context context) in c:\code\cake-targettest-frosting\build\Lifetime.cs:line 15
   --- End of inner exception stack trace ---
   at Lifetime.Setup(Context context) in c:\code\cake-targettest-frosting\build\Lifetime.cs:line 19
   at Cake.Frosting.FrostingLifetime`1.Cake.Frosting.IFrostingSetup.Setup(ICakeContext context)
   at Cake.Frosting.Internal.FrostingEngine`1.<ConfigureLifetime>b__14_0(ISetupContext info)
   at Cake.Core.DefaultExecutionStrategy.PerformSetup(Action`1 action, ISetupContext context)
   at Cake.Core.CakeEngine.PerformSetup(IExecutionStrategy strategy, ICakeContext context, CakeTask targetTask, CakeTask[] tasks, Stopwatch stopWatch, CakeReport report)
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings)
   at Cake.Cli.BuildScriptHost`1.RunTargetAsync(String target)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Cake.Frosting.Internal.FrostingEngine`1.Run(String target)
   at Cake.Frosting.Internal.DefaultCommand.Execute(CommandContext context, DefaultCommandSettings settings)
```

**Comment by charlessolar** [comment]
Aha! Ran into this!

In my case `context.GetArgument("target", "Default")` always returns "Default" even though `./build.ps1 --target "Test"` still targets test.

Great bug report

**Comment by StefanOssendorf** [comment]
A workaround until the problem is solved/my pr approved is to just supply the target twice:
`.\build.ps1 --Target Test -t Test" populates the target into the arguments.
