### ISSUE TITLE
MSBuild: Could not locate executable

### ISSUE THREAD

**Issue by zgdump** [cake-build/cake#3475]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake runner for .NET Framework

### Cake version

1.2.0

### Operating system

Windows

### Operating system architecture

64-Bit

### What are you seeing?

I'm trying Cake for build .NET Framework projects. I wrote a simple script for the test:

```C#
var target = Argument("target", "Test");

Task("Test")
  .Does(() => {
    NuGetRestore("./test/Test.sln");
    MSBuild("./test/Test.sln", new MSBuildSettings {
      Verbosity = Verbosity.Minimal,
      ToolVersion = MSBuildToolVersion.VS2019,
      Configuration = "Release",
    });
  });

RunTarget(target);
```

And get output:
```
Preparing to run build script...
Running build script...

========================================
Test
========================================
MSBuild auto-detection: using msbuild version '16.11.0.36601' from 'C:\Dev\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin'.
All packages listed in packages.config are already installed.
An error occurred when executing task 'Test'.
Error: One or more errors occurred.
        MSBuild: Could not locate executable.
```

Sometimes he found and forcibly used .NET 4.0 from Windows 10, with error at LangVersion. In Visual Studio and Rider, Test.sln building successfully

### What is expected?

Build

### Steps to Reproduce

1. Open Developer PowerShell for Visual Studio 2019
2. Run build.ps1

### Output log

```
Resolving assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' using runtime installed at 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'...
Exception occurred while resolving assembly System.Runtime.Loader: Could not load file or assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' not resolved
Compiling build script...

========================================
Test
========================================
Executing task: Test
Executing: "D:/Projects/goniophotometr/build/tools/NuGet.exe" restore "D:/Projects/goniophotometr/build/measurements/Measurements.sln" -NonInteractive
MSBuild auto-detection: using msbuild version '16.11.0.36601' from 'C:\Dev\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin'.
All packages listed in packages.config are already installed.
An error occurred when executing task 'Test'.
Error: System.AggregateException: One or more errors occurred. ---> Cake.Core.CakeException: MSBuild: Could not locate executable.
   at Cake.Core.Tooling.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Common.Tools.MSBuild.MSBuildAliases.MSBuild(ICakeContext context, FilePath solution, MSBuildSettings settings)
   at Submission#0.MSBuild(FilePath solution, MSBuildSettings settings)
   at Submission#0.<<Initialize>>b__0_0()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass34_0.<Does>b__0(ICakeContext context)
   at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTask>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Cli.BuildScriptHost`1.<RunTargetAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Infrastructure.Scripting.RoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath)
   at Cake.Features.Building.BuildFeature.RunCore(IRemainingArguments arguments, BuildFeatureSettings settings)
   at Cake.Features.Building.BuildFeature.Run(IRemainingArguments arguments, BuildFeatureSettings settings)
   at Cake.Commands.DefaultCommand.Execute(CommandContext context, DefaultCommandSettings settings)
---> (Inner Exception #0) Cake.Core.CakeException: MSBuild: Could not locate executable.
   at Cake.Core.Tooling.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Common.Tools.MSBuild.MSBuildAliases.MSBuild(ICakeContext context, FilePath solution, MSBuildSettings settings)
   at Submission#0.MSBuild(FilePath solution, MSBuildSettings settings)
   at Submission#0.<<Initialize>>b__0_0()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass34_0.<Does>b__0(ICakeContext context)
   at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTask>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Cli.BuildScriptHost`1.<RunTargetAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()<---
```

**Comment by devlead** [comment]
@zgdump if you put the restore in one task and build in another, is it the NuGetRetore och MSBuild alias that fails?
If NuGet which version of [NuGet](https://www.nuget.org/packages/NuGet.CommandLine/) is used? 5.9.x or later required for many solutions.

If Visual Studio isn't installed in any of the standard locations, then I would recommend using one of the [VSWhereAliases](https://cakebuild.net/api/Cake.Common.Tools.VSWhere/VSWhereAliases/), there's a blog post on using it [here ](https://cakebuild.net/blog/2017/03/vswhere-and-visual-studio-2017-support).

If it's a modern CSProj file, looking at the [.NET CLI aliases](https://cakebuild.net/api/Cake.Common.Tools.DotNetCore/DotNetCoreAliases/) might be another option instead of using NuGet.exe and MSBuild.
- [DotNetCoreRestore](https://cakebuild.net/api/Cake.Common.Tools.DotNetCore/DotNetCoreAliases/F533F334)
- [DotNetCoreBuild](https://cakebuild.net/api/Cake.Common.Tools.DotNetCore/DotNetCoreAliases/8E8365A3)
- etc.

**Comment by zgdump** [comment]
@devlead I divide into different tasks, delete work with nuget. The error is same.

I'm tried to use VSWhere:

```C#
#tool nuget:?package=vswhere

DirectoryPath vsLatest  = VSWhereLatest(new VSWhereLatestSettings { Requires = "Microsoft.VisualStudio.Workload.ManagedDesktop"});
FilePath msBuildPathX64 = (vsLatest==null)
                            ? null
                            : vsLatest.CombineWithFilePath("./MSBuild/Current/Bin/MSBuild.exe");

var target = Argument("target", "Test");

Task("Test")
    .Does(() =>
    {
      //NuGetRestore("./test/Test.sln");
      MSBuild("./test/Test.sln", new MSBuildSettings {
      ToolPath = msBuildPathX64,
    });
});

RunTarget(target);
```

It almost worked, though he is now trying to use the ancient and built-in.NET 4.0 from Windows:

```
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Csc.exe
```

As a consequence, the error:

```
CSC : error CS1617: Invalid option '8' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default [...\build\measurements\test\Test.csproj]
```

My project needs .NET Framework 4.6

**Comment by augustoproiete** [comment]
(moving to GitHub discussions)
