### ISSUE TITLE
VSTest Alias does not work when only VS 2022 Preview is installed

### ISSUE THREAD

**Issue by nils-a** [cake-build/cake#3772]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake .NET Tool

### Cake version

2.0.0

### Operating system

Windows

### Operating system architecture

64-Bit

### CI Server

none

### What are you seeing?

`VSTest` errors out with the exception "Could not load executable".
One of my machines is running VS 2022-preview, one is running VS 2022-professional. Both have VS2019 build tools installed additionally.

### What is expected?

Since `VSTest` is part of VS2022 (all editions) and VS2019 build tools I would expect `VSTest` to work on both machines.

This bug is partially related to #3708 and #3464 where probably VS2022 and VS2019 build tools should have been added to https://github.com/cake-build/cake/blob/a7f023d7ddfeb0dbd24e86bef89eb4f402380584/src/Cake.Common/Tools/VSTest/VSTestRunner.cs#L153

### Steps to Reproduce

Remove all VS versions but [VS2022 | VS2019 build tools] and use `VSTest`
Use the following task:
```csharp
Task("Default")
.Does(() => {
   var files = GetFiles(File("**/*.csproj").Path.FullPath);
   VSTest(files);
});
```

### Output log

```text
Error: System.AggregateException: One or more errors occurred. (VSTest: Could not locate executable.)
 ---> Cake.Core.CakeException: VSTest: Could not locate executable.
   at Cake.Core.Tooling.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 164
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 81
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 60
   at Cake.Common.Tools.VSTest.VSTestRunner.Run(IEnumerable`1 assemblyPaths, VSTestSettings settings) in C:\projects\cake\src\Cake.Common\Tools\VSTest\VSTestRunner.cs:line 57
   at Cake.Common.Tools.VSTest.VSTestAliases.VSTest(ICakeContext context, IEnumerable`1 assemblyPaths, VSTestSettings settings) in C:\projects\cake\src\Cake.Common\Tools\VSTest\VSTestAliases.cs:line 120
   at Cake.Common.Tools.VSTest.VSTestAliases.VSTest(ICakeContext context, IEnumerable`1 assemblyPaths) in C:\projects\cake\src\Cake.Common\Tools\VSTest\VSTestAliases.cs:line 92
   at Submission#0.VSTest(IEnumerable`1 assemblyPaths)
   at Submission#0.<<Initialize>>b__0_2()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass31_0.<Does>b__0(ICakeContext _) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 26    
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass34_0.<Does>b__0(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 81
   at Cake.Core.CakeTask.Execute(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTask.cs:line 119
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context) in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 72     
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 322
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 345
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 355
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 258
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 221
   at Cake.Cli.BuildScriptHost`1.RunTargetAsync(String target) in C:\projects\cake\src\Cake.Cli\Hosts\BuildScriptHost.cs:line 73
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 105
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Infrastructure.Scripting.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Infrastructure\Scripting\RoslynScriptSession.cs:line 86  
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 172
   at Cake.Features.Building.BuildFeature.RunCore(IRemainingArguments arguments, BuildFeatureSettings settings) in C:\projects\cake\src\Cake\Features\Building\BuildFeature.cs:line 99
   at Cake.Features.Building.BuildFeature.Run(IRemainingArguments arguments, BuildFeatureSettings settings) in C:\projects\cake\src\Cake\Features\Building\BuildFeature.cs:line 49
   at Cake.Commands.DefaultCommand.Execute(CommandContext context, DefaultCommandSettings settings) in C:\projects\cake\src\Cake\Commands\DefaultCommand.cs:line 73  
```

**Comment by nils-a** [comment]
`MSTest` has a [very similar logic](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/MSTest/MSTestRunner.cs#L115), perhaps it needs modification, too.
