### ISSUE TITLE
Cake.AndroidSDKManager always crashes when no SDK is installed

### ISSUE THREAD

**Issue by nick5454** [cake-build/cake#3803]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake runner for .NET Core

### Cake version

1.1.0

### Operating system

macOS

### Operating system architecture

64-Bit

### CI Server

Azure Devops

### What are you seeing?

I am getting an exception on GetAlternateToolPaths and no Android SDK's exist on the clean MacOs MS Host in Azure. This is reproducible locally if your Android SDK's are not in your path ( Environment Variable's Path )

### What is expected?

the Cake.AndroidSDKManager should return an empty list of SDK's on the AndroidSDKManagerList.InstalledPackages

### Steps to Reproduce

Any PC or Mac that does not have Android SDK Directories in the Path environment variable will cause this error.

See attached cake build. change the #tool to the nuget. 

Everytime it runs and does not find an SDK, it throws an exceptio
[Cake.Local.Test.zip](https://github.com/cake-build/cake/files/7962302/Cake.Local.Test.zip)
n

### Output log

```
Preparing to run build script...
Tools: C:\Repos\Cake.Local.Test\tools       
Tools: C:\Repos\Cake.Local.Test\tools\Addins
Start testing Cake path.
Running build script...
Looking for modules...
No modules found to install.
Module directory does not exist.
Analyzing build script...
Analyzing C:/Repos/Cake.Local.Test/recipe.cake...
Processing build script...
Installing tools...
The 'tool' directive is attempting to install the 'Cake.Android.SdkManager' package 
without specifying a package version number.
More information on this can be found at https://cakebuild.net/docs/writing-builds/reproducible-builds/
It's not recommended, but you can explicitly override this warning
by configuring the Skip Package Version Check setting to true
(i.e. command line parameter "--settings_skippackageversioncheck=true",
environment variable "CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK=true",
read more about configuration at https://cakebuild.net/docs/running-builds/configuration/)
Missing C:\Users\NickTurner\.nuget\packages\cake.android.sdkmanager\3.0.2\cake.android.sdkmanager.3.0.2.nupkg
Installing addins...
The 'addin' directive is attempting to install the 'Cake.Android.SdkManager' package 
without specifying a package version number.
More information on this can be found at https://cakebuild.net/docs/writing-builds/reproducible-builds/
It's not recommended, but you can explicitly override this warning
by configuring the Skip Package Version Check setting to true
(i.e. command line parameter "--settings_skippackageversioncheck=true",
environment variable "CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK=true",
read more about configuration at https://cakebuild.net/docs/running-builds/configuration/)
Missing C:\Users\NickTurner\.nuget\packages\cake.android.sdkmanager\3.0.2\cake.android.sdkmanager.3.0.2.nupkg
The addin Cake.Android.SdkManager will reference Cake.Android.SdkManager.dll.
Verifying assembly 'Cake.Android.SdkManager, Version=3.0.2.0, Culture=neutral, PublicKeyToken=null'.
The assembly 'Cake.Android.SdkManager, Version=3.0.2.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.33.0).
For best compatibility it should target Cake.Core version 1.0.0.
Adding assembly reference to System.Private.CoreLib.dll...
Adding assembly reference to System.Linq.Expressions.dll...
Adding assembly reference to Microsoft.CSharp.dll...
Adding assembly reference to Cake.Core.dll...
Adding assembly reference to Cake.Common.dll...
Adding assembly reference to netstandard.dll...
Adding assembly reference to Microsoft.Win32.Registry.dll...
Adding assembly reference to Cake.Android.SdkManager.dll...
Importing namespace Cake.AndroidSdkManager...
Importing namespace Cake.Common...
Importing namespace Cake.Common.Build...
Importing namespace Cake.Common.Build.AppVeyor...
Importing namespace Cake.Common.Build.AppVeyor.Data...
Importing namespace Cake.Common.Build.AzurePipelines...
Importing namespace Cake.Common.Build.AzurePipelines.Data...
Importing namespace Cake.Common.Build.Bamboo...
Importing namespace Cake.Common.Build.Bamboo.Data...
Importing namespace Cake.Common.Build.BitbucketPipelines...
Importing namespace Cake.Common.Build.BitbucketPipelines.Data...
Importing namespace Cake.Common.Build.Bitrise...
Importing namespace Cake.Common.Build.Bitrise.Data...
Importing namespace Cake.Common.Build.ContinuaCI...
Importing namespace Cake.Common.Build.ContinuaCI.Data...
Importing namespace Cake.Common.Build.GitHubActions...
Importing namespace Cake.Common.Build.GitHubActions.Data...
Importing namespace Cake.Common.Build.GitLabCI...
Importing namespace Cake.Common.Build.GitLabCI.Data...
Importing namespace Cake.Common.Build.GoCD...
Importing namespace Cake.Common.Build.GoCD.Data...
Importing namespace Cake.Common.Build.Jenkins...
Importing namespace Cake.Common.Build.Jenkins.Data...
Importing namespace Cake.Common.Build.MyGet...
Importing namespace Cake.Common.Build.TeamCity...
Importing namespace Cake.Common.Build.TravisCI...
Importing namespace Cake.Common.Build.TravisCI.Data...
Importing namespace Cake.Common.Diagnostics...
Importing namespace Cake.Common.IO...
Importing namespace Cake.Common.IO.Paths...
Importing namespace Cake.Common.Net...
Importing namespace Cake.Common.Security...
Importing namespace Cake.Common.Solution...
Importing namespace Cake.Common.Solution.Project...
Importing namespace Cake.Common.Solution.Project.Properties...
Importing namespace Cake.Common.Solution.Project.XmlDoc...
Importing namespace Cake.Common.Text...
Importing namespace Cake.Common.Tools.Cake...
Importing namespace Cake.Common.Tools.Chocolatey...
Importing namespace Cake.Common.Tools.Chocolatey.ApiKey...
Importing namespace Cake.Common.Tools.Chocolatey.Config...
Importing namespace Cake.Common.Tools.Chocolatey.Download...
Importing namespace Cake.Common.Tools.Chocolatey.Features...
Importing namespace Cake.Common.Tools.Chocolatey.Install...
Importing namespace Cake.Common.Tools.Chocolatey.New...
Importing namespace Cake.Common.Tools.Chocolatey.Pack...
Importing namespace Cake.Common.Tools.Chocolatey.Pin...
Importing namespace Cake.Common.Tools.Chocolatey.Push...
Importing namespace Cake.Common.Tools.Chocolatey.Sources...
Importing namespace Cake.Common.Tools.Chocolatey.Uninstall...
Importing namespace Cake.Common.Tools.Chocolatey.Upgrade...
Importing namespace Cake.Common.Tools.DotCover...
Importing namespace Cake.Common.Tools.DotCover.Analyse...
Importing namespace Cake.Common.Tools.DotCover.Cover...
Importing namespace Cake.Common.Tools.DotCover.Merge...
Importing namespace Cake.Common.Tools.DotCover.Report...
Importing namespace Cake.Common.Tools.DotNetCore...
Importing namespace Cake.Common.Tools.DotNetCore.Build...
Importing namespace Cake.Common.Tools.DotNetCore.BuildServer...
Importing namespace Cake.Common.Tools.DotNetCore.Clean...
Importing namespace Cake.Common.Tools.DotNetCore.Execute...
Importing namespace Cake.Common.Tools.DotNetCore.MSBuild...
Importing namespace Cake.Common.Tools.DotNetCore.NuGet.Delete...
Importing namespace Cake.Common.Tools.DotNetCore.NuGet.Push...
Importing namespace Cake.Common.Tools.DotNetCore.NuGet.Source...
Importing namespace Cake.Common.Tools.DotNetCore.Pack...
Importing namespace Cake.Common.Tools.DotNetCore.Publish...
Importing namespace Cake.Common.Tools.DotNetCore.Restore...
Importing namespace Cake.Common.Tools.DotNetCore.Run...
Importing namespace Cake.Common.Tools.DotNetCore.Test...
Importing namespace Cake.Common.Tools.DotNetCore.Tool...
Importing namespace Cake.Common.Tools.DotNetCore.VSTest...
Importing namespace Cake.Common.Tools.DupFinder...
Importing namespace Cake.Common.Tools.Fixie...
Importing namespace Cake.Common.Tools.GitLink...
Importing namespace Cake.Common.Tools.GitReleaseManager...
Importing namespace Cake.Common.Tools.GitReleaseManager.AddAssets...
Importing namespace Cake.Common.Tools.GitReleaseManager.Close...
Importing namespace Cake.Common.Tools.GitReleaseManager.Create...
Importing namespace Cake.Common.Tools.GitReleaseManager.Discard...
Importing namespace Cake.Common.Tools.GitReleaseManager.Export...
Importing namespace Cake.Common.Tools.GitReleaseManager.Label...
Importing namespace Cake.Common.Tools.GitReleaseManager.Open...
Importing namespace Cake.Common.Tools.GitReleaseManager.Publish...
Importing namespace Cake.Common.Tools.GitReleaseNotes...
Importing namespace Cake.Common.Tools.GitVersion...
Importing namespace Cake.Common.Tools.ILMerge...
Importing namespace Cake.Common.Tools.ILRepack...
Importing namespace Cake.Common.Tools.InnoSetup...
Importing namespace Cake.Common.Tools.InspectCode...
Importing namespace Cake.Common.Tools.MSBuild...
Importing namespace Cake.Common.Tools.MSpec...
Importing namespace Cake.Common.Tools.MSTest...
Importing namespace Cake.Common.Tools.NSIS...
Importing namespace Cake.Common.Tools.NuGet...
Importing namespace Cake.Common.Tools.NuGet.Add...
Importing namespace Cake.Common.Tools.NuGet.Delete...
Importing namespace Cake.Common.Tools.NuGet.Init...
Importing namespace Cake.Common.Tools.NuGet.Install...
Importing namespace Cake.Common.Tools.NuGet.List...
Importing namespace Cake.Common.Tools.NuGet.Pack...
Importing namespace Cake.Common.Tools.NuGet.Push...
Importing namespace Cake.Common.Tools.NuGet.Restore...
Importing namespace Cake.Common.Tools.NuGet.SetApiKey...
Importing namespace Cake.Common.Tools.NuGet.SetProxy...
Importing namespace Cake.Common.Tools.NuGet.Sources...
Importing namespace Cake.Common.Tools.NuGet.Update...
Importing namespace Cake.Common.Tools.NUnit...
Importing namespace Cake.Common.Tools.OctopusDeploy...
Importing namespace Cake.Common.Tools.OpenCover...
Importing namespace Cake.Common.Tools.ReportGenerator...
Importing namespace Cake.Common.Tools.ReportUnit...
Importing namespace Cake.Common.Tools.Roundhouse...
Importing namespace Cake.Common.Tools.SignTool...
Importing namespace Cake.Common.Tools.SpecFlow...
Importing namespace Cake.Common.Tools.SpecFlow.StepDefinitionReport...
Importing namespace Cake.Common.Tools.SpecFlow.TestExecutionReport...
Importing namespace Cake.Common.Tools.TextTransform...
Importing namespace Cake.Common.Tools.VSTest...
Importing namespace Cake.Common.Tools.VSWhere...
Importing namespace Cake.Common.Tools.VSWhere.All...
Importing namespace Cake.Common.Tools.VSWhere.Latest...
Importing namespace Cake.Common.Tools.VSWhere.Legacy...
Importing namespace Cake.Common.Tools.VSWhere.Product...
Importing namespace Cake.Common.Tools.WiX...
Importing namespace Cake.Common.Tools.WiX.Heat...
Importing namespace Cake.Common.Tools.XBuild...
Importing namespace Cake.Common.Tools.XUnit...
Importing namespace Cake.Common.Xml...
Importing namespace Cake.Core...
Importing namespace Cake.Core.Diagnostics...
Importing namespace Cake.Core.IO...
Importing namespace Cake.Core.Scripting...
Importing namespace System...
Importing namespace System.Collections.Generic...
Importing namespace System.IO...
Importing namespace System.Linq...
Importing namespace System.Text...
Importing namespace System.Threading.Tasks...
Compiling build script...

========================================
Build
========================================
Executing task: Build
Target:Build
Started Version Check
settings.SdkRoot is null
Could not resolve path for tool "sdkmanager" using these directories: C:/Users/NickTurner/.dotnet/tools/.store/powershell/7.2.0/powershell/7.2.0/tools/net6.0/any/win,C:/Program Files/Microsoft MPI/Bin,C:/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin,C:/Program Files/Common Files/Microsoft Shared/Microsoft Online Services,C:/Program Files (x86)/Common Files/Microsoft Shared/Microsoft Online Services,C:/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler,C:/Python39/Scripts,C:/Python39,C:/windows/system32,C:/windows,C:/windows/System32/Wbem,C:/windows/System32/WindowsPowerShell/v1.0,C:/windows/System32/OpenSSH,C:/Program Files/dotnet,C:/Program Files/Microsoft SQL Server/130/Tools/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn,C:/Program Files/Azure Data Studio/bin,C:/ProgramData/chocolatey/bin,C:/Program Files/nodejs,C:/Program Files/Microsoft VS Code/bin,C:/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn,C:/Program Files/Microsoft SQL Server/150/Tools/Binn,C:/Program 
Files/Microsoft SQL Server/150/DTS/Binn,C:/Program Files/Git/cmd,C:/Program Files (x86)/dotnet,C:/Users/NickTurner/AppData/Local/Microsoft/WindowsApps,C:/Users/NickTurner/.dotnet/tools,C:/Program Files/Azure Data Studio/bin,C:/Users/NickTurner/AppData/Roaming/npm,C:/Users/NickTurner/.nuget/packages/nuget.commandline/5.7.0/tools,C:/Users/NickTurner/AppData/Local/Programs/Fiddler,C:/Users/NickTurner/.dotnet/tools,C:/Users/NickTurner/.azure/bin
Could not resolve path for tool "sdkmanager.bat" using these directories: C:/Users/NickTurner/.dotnet/tools/.store/powershell/7.2.0/powershell/7.2.0/tools/net6.0/any/win,C:/Program Files/Microsoft MPI/Bin,C:/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin,C:/Program Files/Common Files/Microsoft Shared/Microsoft Online Services,C:/Program Files (x86)/Common Files/Microsoft Shared/Microsoft Online Services,C:/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler,C:/Python39/Scripts,C:/Python39,C:/windows/system32,C:/windows,C:/windows/System32/Wbem,C:/windows/System32/WindowsPowerShell/v1.0,C:/windows/System32/OpenSSH,C:/Program Files/dotnet,C:/Program Files/Microsoft SQL Server/130/Tools/Binn,C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn,C:/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn,C:/Program Files/Azure Data Studio/bin,C:/ProgramData/chocolatey/bin,C:/Program Files/nodejs,C:/Program Files/Microsoft VS Code/bin,C:/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn,C:/Program Files/Microsoft SQL Server/150/Tools/Binn,C:/Program Files/Microsoft SQL Server/150/DTS/Binn,C:/Program Files/Git/cmd,C:/Program Files (x86)/dotnet,C:/Users/NickTurner/AppData/Local/Microsoft/WindowsApps,C:/Users/NickTurner/.dotnet/tools,C:/Program Files/Azure Data Studio/bin,C:/Users/NickTurner/AppData/Roaming/npm,C:/Users/NickTurner/.nuget/packages/nuget.commandline/5.7.0/tools,C:/Users/NickTurner/AppData/Local/Programs/Fiddler,C:/Users/NickTurner/.dotnet/tools,C:/Users/NickTurner/.azure/bin
Begin checking home
Finished checking home
An error occurred when executing task 'Build'.
Error: System.AggregateException: One or more errors occurred. (sdkmanager: Could not locate executable.) ---> Cake.Core.CakeException: sdkmanager: Could not locate executable.
   at Cake.AndroidSdkManager.ToolEx.RunProcessEx(AndroidSdkManagerToolSettings settings, ProcessArgumentBuilder arguments)
   at Cake.AndroidSdkManager.AndroidSdkManagerTool.CheckSdkManagerVersion(AndroidSdkManagerToolSettings settings)
   at Cake.AndroidSdkManager.AndroidSdkManagerTool.List(AndroidSdkManagerToolSettings settings)
   at Submission#0.AndroidSdkManagerList(AndroidSdkManagerToolSettings settings)
   at Submission#0.<<Initialize>>b__0_0()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass32_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 82
   at Cake.Core.CakeTask.Execute(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTask.cs:line 119
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context) in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 74
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 278
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 301
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 311
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 226
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 189
   at Cake.Cli.BuildScriptHost`1.RunTargetAsync(String target) in C:\projects\cake\src\Cake.Cli\Hosts\BuildScriptHost.cs:line 73
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 105
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)  
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Infrastructure.Scripting.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Infrastructure\Scripting\RoslynScriptSession.cs:line 143
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 173
   at Cake.Features.Building.BuildFeature.RunCore(IRemainingArguments arguments, BuildFeatureSettings settings) in C:\projects\cake\src\Cake\Features\Building\BuildFeature.cs:line 90
   at Cake.Features.Building.BuildFeature.Run(IRemainingArguments arguments, BuildFeatureSettings settings) in C:\projects\cake\src\Cake\Features\Building\BuildFeature.cs:line 49
   at Cake.Commands.DefaultCommand.Execute(CommandContext context, DefaultCommandSettings settings) in C:\projects\cake\src\Cake\Commands\DefaultCommand.cs:line 72
---> (Inner Exception #0) Cake.Core.CakeException: sdkmanager: Could not locate executable.
   at Cake.AndroidSdkManager.ToolEx.RunProcessEx(AndroidSdkManagerToolSettings settings, ProcessArgumentBuilder arguments) 
   at Cake.AndroidSdkManager.AndroidSdkManagerTool.CheckSdkManagerVersion(AndroidSdkManagerToolSettings settings)
   at Cake.AndroidSdkManager.AndroidSdkManagerTool.List(AndroidSdkManagerToolSettings settings)
   at Submission#0.AndroidSdkManagerList(AndroidSdkManagerToolSettings settings)
   at Submission#0.<<Initialize>>b__0_0()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass32_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 82
   at Cake.Core.CakeTask.Execute(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTask.cs:line 119
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context) in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 74
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 278
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 301
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 311
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 226
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 189
   at Cake.Cli.BuildScriptHost`1.RunTargetAsync(String target) in C:\projects\cake\src\Cake.Cli\Hosts\BuildScriptHost.cs:line 73
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 105
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)  
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)<---
```

**Comment by gep13** [comment]
@nick5454 are you talking about this addin:

https://github.com/cake-contrib/Cake.Android.SdkManager

If so, this repository is not the right place to ask questions about this.

**Comment by nick5454** [comment]
I'm closing this, because there are a lot of issues with the extension. I'll create a PR in the extension for the fixes.
