### ISSUE TITLE
The #addin directive should import referenced aliases

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#415]
If a NuGet package (added with the `#addin` directive) reference another assembly in the package that contains an alias, it will not be referenced properly.

(Reported by @jrnail23 in #382)

**Comment by jrnail23** [comment]
@patriksvensson, I'm not entirely convinced this is what's actually going on here.

I'm going to investigate a bit more -- this could just be something I'm doing wrong.

**Comment by patriksvensson** [comment]
@jrnail23 Ok, perfect!

**Comment by jrnail23** [comment]
@patriksvensson, I'm thorougly confused now.

I made a really simple cake script that uses my addins:

```C#
#r "./tools/Cake.IISExpress/lib/net45/Cake.IISExpress.dll"
#r "./tools/Cake.Process/lib/net45/Cake.Process.dll"
using Cake.IISExpress;
using Cake.Process;

      // ARGUMENTS
      var target = Argument("target", "Default");

      Task("Something")
          .Does(cc =>
          {
              Verbose(cc.Environment.WorkingDirectory.FullPath);
          });

      Task("Default")
          .IsDependentOn("Something");

      RunTarget(target);
```

Here's the console output from when I run it:
```
PS C:\Dev\oss\Cake.IISExpress\src\Examples> .\build.ps1 -Script Example2.cake -Verbosity Diagnostic
All packages listed in packages.config are already installed.
Processing Example2.cake...
Adding Reference: C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake.IISExpress/lib/net45/Cake.IISExpress.dll
Adding Reference: C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake.Process/lib/net45/Cake.Process.dll
Creating script session...
Could not find file Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null.
System.IO.FileNotFoundException: Could not load file or assembly 'Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at Cake.Core.Scripting.ScriptAliasFinder.GetParameters(MethodInfo method, ICakeLog log)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Error: System.IO.FileNotFoundException: Could not load file or assembly 'Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at Cake.Core.Scripting.ScriptAliasFinder.GetParameters(MethodInfo method, ICakeLog log)
   at Cake.Core.Scripting.ScriptAliasFinder.<GetAliasMethods>d__0.MoveNext()
   at Cake.Core.Scripting.ScriptAliasFinder.FindAliases(IEnumerable`1 assemblies)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(IEnumerable`1 args)
```

It appears to add the reference to both of my dlls (Cake.Process.dll and Cake.IISExpress.dll), but then when it tries to find the aliases, it says it can't find the Cake.Process.dll.

You have any idea what's going on here?

**Comment by patriksvensson** [comment]
@jrnail23 Can you enable the fusion log and paste the input here? Would be interesting to see how the runtime tries to resolve the `Cake.Process.dll` assembly.

**Comment by jrnail23** [comment]
Here's the output with fusion log enabled:

```
PS C:\Dev\oss\Cake.IISExpress\src\Examples> .\build.ps1 -Script Example2.cake -Verbosity Diagnostic
All packages listed in packages.config are already installed.
Processing Example2.cake...
Adding Reference: C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake.IISExpress/lib/net45/Cake.IISExpress.dll
Adding Reference: C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake.Process/lib/net45/Cake.Process.dll
Creating script session...
Could not find file Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null.
System.IO.FileNotFoundException: Could not load file or assembly 'Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at Cake.Core.Scripting.ScriptAliasFinder.GetParameters(MethodInfo method, ICakeLog log)

=== Pre-bind state information ===
LOG: DisplayName = Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: The same bind was seen before, and was failed with hr = 0x80070002.

Error: System.IO.FileNotFoundException: Could not load file or assembly 'Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at Cake.Core.Scripting.ScriptAliasFinder.GetParameters(MethodInfo method, ICakeLog log)
   at Cake.Core.Scripting.ScriptAliasFinder.<GetAliasMethods>d__0.MoveNext()
   at Cake.Core.Scripting.ScriptAliasFinder.FindAliases(IEnumerable`1 assemblies)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(IEnumerable`1 args)

=== Pre-bind state information ===
LOG: DisplayName = Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
```

**Comment by jrnail23** [comment]
Here's my fusion log for Cake.Process:

```
*** Assembly Binder Log Entry  (9/14/2015 @ 9:17:39 PM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Dev\oss\Cake.IISExpress\src\Examples\tools\Cake\Cake.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = Cake.exe
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/Cake.Process.DLL.
LOG: Attempting download of new URL file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/Cake.Process/Cake.Process.DLL.
LOG: Attempting download of new URL file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/Cake.Process.EXE.
LOG: Attempting download of new URL file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/Cake.Process/Cake.Process.EXE.
LOG: All probing URLs attempted and failed.

*** Assembly Binder Log Entry  (9/14/2015 @ 9:17:39 PM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Dev\oss\Cake.IISExpress\src\Examples\tools\Cake\Cake.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = Cake.exe
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/Cake.Process.DLL.
LOG: Attempting download of new URL file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/Cake.Process/Cake.Process.DLL.
LOG: Attempting download of new URL file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/Cake.Process.EXE.
LOG: Attempting download of new URL file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/Cake.Process/Cake.Process.EXE.
LOG: All probing URLs attempted and failed.

*** Assembly Binder Log Entry  (9/14/2015 @ 9:17:39 PM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Dev\oss\Cake.IISExpress\src\Examples\tools\Cake\Cake.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Cake.Process, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = Cake.exe
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
ERR: Unrecoverable error occurred during pre-download check (hr = 0x80070002).
```

**Comment by jrnail23** [comment]
Here's an additional Fusion log: 

```
*** Assembly Binder Log Entry  (9/14/2015 @ 9:39:42 PM) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Dev\oss\Cake.IISExpress\src\Examples\tools\Cake\Cake.exe
--- A detailed error log follows. 

LOG: IJW explicit bind. File path:C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake.Process/lib/net45/Cake.Process.dll.
LOG: IJW assembly bind returned file not found.

*** Assembly Binder Log Entry  (9/14/2015 @ 9:39:42 PM) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Dev\oss\Cake.IISExpress\src\Examples\tools\Cake\Cake.exe
--- A detailed error log follows. 

LOG: IJW explicit bind. File path:C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake.Process/lib/net45/Cake.Process.dll.
LOG: IJW assembly bind returned file not found.
```

That path that's returning file not found (`C:/Dev/oss/Cake.IISExpress/src/Examples/tools/Cake.Process/lib/net45/Cake.Process.dll`) does in fact exist on my machine.

**Comment by patriksvensson** [comment]
Ok, the problem lies within the ScriptRunner which uses `Assembly.LoadFile` instead of `Assembly.LoadFrom`. Should be changed but we need to examine the implications of this.

See http://blogs.msdn.com/b/suzcook/archive/2003/05/29/57143.aspx for more information.
