### ISSUE TITLE
XUnit command line bug

### ISSUE THREAD

**Issue by jeffdoolittle** [cake-build/cake#744]
The XUnit command line doesn't work anymore on the latest version of Cake. It appears to be attempting to send multiple test dlls as command line parameters which is not allowed for XUnit. See the diagnostic output below.

Perhaps XUnit2 allows this and that is the reason for the regression?

========================================
Run-Unit-Tests
========================================
Executing task: Run-Unit-Tests
Executing: "C:/Projects/MyProject/tools/xunit.runners/tools/xunit.console.clr4.exe" "C:/Projects/MyProject/src/MyProject.Api.Tests/bin/Debug/MyProject.Api.Tests
.dll" "C:/Projects/MyProject/src/MyProject.Model.Tests/bin/Debug/MyProject.Model.Tests.dll" "/html" "C:/Projects/MyProject/build/test-results/TestResults.html"
"/xml" "C:/Projects/MyProject/build/test-results/TestResults.xml"
xUnit.net console test runner (64-bit .NET 4.0.30319.42000)
Copyright (C) 2013 Outercurve Foundation.

xunit.dll:     Version 1.9.2.1705
Test assembly: C:\Projects\MyProject\src\MyProject.Api.Tests\bin\Debug\MyProject.Api.Tests.dll

Given a browser when authorizing as valid user, should have status code OK [FAIL]
   System.Configuration.ConfigurationErrorsException : Configuration system failed to initialize
   ---- System.Configuration.ConfigurationErrorsException : Data at the root level is invalid. Line 1, position 1. (C:\Projects\MyProject\src\MyProject.Model.Tests\bin\De
bug\MyProject.Model.Tests.dll line 1)
   -------- System.Xml.XmlException : Data at the root level is invalid. Line 1, position 1.
   Stack Trace:
      at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
      at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
      at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
      at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
      at System.Diagnostics.DiagnosticsConfiguration.Initialize()
      at System.Diagnostics.DiagnosticsConfiguration.get_IndentSize()
      at System.Diagnostics.TraceInternal.InitializeSettings()
      at System.Diagnostics.TraceInternal.get_Listeners()
      at System.Diagnostics.Trace.get_Listeners()
      at Xunit.Sdk.ExceptionAndOutputCaptureCommand.Execute(Object testClass)
   ----- Inner Stack Trace -----
      at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
      at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
      at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   ----- Inner Stack Trace -----
      at System.Xml.XmlTextReaderImpl.Throw(Exception e)
      at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
      at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
      at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
      at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

42 total, 1 failed, 0 skipped, took 4.283 seconds
An error occured when executing task 'Run-Unit-Tests'.
Error: Cake.Core.CakeException: xUnit.net (v1): Process returned an error (exit code 1).
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Common.Tools.XUnit.XUnitRunner.Run(IEnumerable`1 assemblyPaths, XUnitSettings settings)
   at Submission#0.<.ctor>b__8()
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(IEnumerable`1 args)

**Comment by jeffdoolittle** [comment]
Cake build configuration:

```
Task("Run-Unit-Tests")
	.IsDependentOn("Build-Solution")
	.Does(() =>
{
	XUnit("./src/**/bin/" + configuration + "/*.Tests.dll", new XUnitSettings {
		OutputDirectory = testResultsDir,
		XmlReport = true,
		HtmlReport = true
	});
});
```

**Comment by jeffdoolittle** [comment]
note: the problem goes away if there is only one assembly matching the search parameters.

**Comment by devlead** [comment]
@jeffdoolittle yes would seem to be a regression, XUnit2 does allow sending multiple assemblies.

**Comment by devlead** [comment]
@jeffdoolittle I've proposed a fix with pr #745 for this issue, you can if you have the opportunity download and test if that solves your issue [here](https://ci.appveyor.com/project/cakebuild/cake/build/0.9.0-PullRequest0745/artifacts)

And @patriksvensson or @gep13  would be great if one of you could review and merge that tomorrow if it fixes the issue.

Sorry for the inconvenience @jeffdoolittle, we'll try to sort this as quick as possible.

**Comment by jeffdoolittle** [comment]
thanks for the quick turnaround on this! works like a charm.

**Comment by devlead** [comment]
Glad to hear @jeffdoolittle :+1:

**Comment by jeffdoolittle** [comment]
any possibility of a 0.9.1 drop to get this fix out sooner?

**Comment by devlead** [comment]
@jeffdoolittle we'll do a 0.10.0 release this week.

**Comment by jeffdoolittle** [comment]
ah, ok! thanks.

**Comment by jeffdoolittle** [comment]
eta on a new nuget package?

**Comment by patriksvensson** [comment]
@jeffdoolittle The 0.10.0 release is out now! :smile:

**Comment by jeffdoolittle** [comment]
yay thanks!
