### ISSUE TITLE
Report test coverage for Cake to Coveralls.io

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#856]
It would be good to be able to report on/view the test coverage within Cake.  We should add this into the build.cake file, and report it to Coveralls.io.

Depends on https://github.com/cake-build/cake/issues/464

**Comment by gep13** [comment]
This will be possible very soon, after this is published:

https://github.com/gep13/Cake.Coveralls

**Comment by gep13** [comment]
Looks like there is an issue pushing the report.

https://ci.appveyor.com/project/cakebuild/cake/build/0.16.0-alpha.55.build.2654#L1382

Will investigate.

**Comment by devlead** [comment]
Doesn't seem to be working well on our Jenkins
```
========================================
Run-Unit-Tests
========================================
Executing task: Run-Unit-Tests
At: Program.Main
An System.ComponentModel.Win32Exception occured: Access is denied
stack:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at OpenCover.Framework.ProfilerRegistration.ExecuteProcess(ProcessStartInfo psi) in c:\projects\opencover\main\OpenCover.Framework\ProfilerRegistration.cs:line 75
   at OpenCover.Framework.ProfilerRegistration.ExecuteRegsvr32(Boolean userRegistration, Boolean register, Boolean is64) in c:\projects\opencover\main\OpenCover.Framework\ProfilerRegistration.cs:line 97
   at OpenCover.Console.Program.RunWithContainer(CommandLineParser parser, Bootstrapper container, IPersistance persistance) in c:\projects\opencover\main\OpenCover.Console\Program.cs:line 178
   at OpenCover.Console.Program.Main(String[] args) in c:\projects\opencover\main\OpenCover.Console\Program.cs:line 70
A report has been sent to the OpenCover development team.
If you are unable to resolve the issue please contact the OpenCover development team
see https://www.github.com/opencover/opencover/issues
An error occured when executing task 'Run-Unit-Tests'.
Error: OpenCover: Process returned an error (exit code 1).
Build step 'Windows PowerShell' marked build as failure
Finished: FAILURE
```
http://cake-jenkins.azurewebsites.net/job/Cake/223/console

**Comment by gep13** [comment]
Now that the Jenkins build is up and running again, closing to close this off as complete
