### ISSUE TITLE
VSTS integration fails passing Argument

### ISSUE THREAD

**Issue by dachibox** [cake-build/cake#983]
### What You Are Seeing?
I'm trying to zip an Universal Windows Platform AppPackage. But passing -zipDir:"$(Build.BinariesDirectory)\" fails on vsts. Locally just works.
### What version of Cake are you using?
Version 0.13.0+Branch.main.Sha.f7346f2a5fb4e19a24cf15780ce635529f921be4
### Are you running on a 32 or 64 bit system?
64 bit system locally
### What environment are you running on?  Windows? Linux? Mac?
Windows 10 (10586)
### Are you running on a CI Server?  If so, which one?
Visual Studio Team Services on the Host.

### How Did You Get This To Happen? (Steps to Reproduce)

I think on the VSTS, Argument is not passing in VSTS. On Output Log we can see that it is passing this: -zipDir:"C:\a\1\b\" but on the System.Exception (I'm calling) zipDir is "./" (Default value).

**build.cake**
var zipDir = Argument("zipDir","./");

**build.ps1**
.PARAMETER ZipDir
[string]$ZipDir = "./",
-zipDir=`"$ZipDir`"

**Sample of the code:**
[CakeContinuousIntegration](https://github.com/dachibox/Demos/tree/feature/Cake/CakeContinuousIntegration)

**I will add some screenshots how I condigure VSTS for this:**
![buildsolution](https://cloud.githubusercontent.com/assets/1771785/15980874/18623876-2f6f-11e6-8ab5-6d7fb38d528f.png)
![cakezippackage](https://cloud.githubusercontent.com/assets/1771785/15980879/202bfb5a-2f6f-11e6-969e-b04fa253980a.png)

### Output Log
2016-06-10T22:40:35.2224898Z Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.100.4\tasks\Cake\0.1.6\Cake.ps1
2016-06-10T22:40:35.3364887Z Restoring packages...
2016-06-10T22:40:35.6354871Z All packages listed in packages.config are already installed.
**2016-06-10T22:40:35.6434872Z C:\a\1\s\tools\Cake\Cake.exe "C:\a\1\s\build.cake" -target="Zip-Package" -verbosity="Diagnostic" -zipDir:"C:\a\1\b\"**
2016-06-10T22:40:35.8894855Z Module directory does not exist.
2016-06-10T22:40:35.9504844Z Analyzing build script...
2016-06-10T22:40:35.9604844Z Analyzing C:/a/1/s/build.cake...
2016-06-10T22:40:35.9764860Z Processing build script...
2016-06-10T22:40:35.9784850Z Installing tools...
2016-06-10T22:40:35.9835069Z Package NUnit.ConsoleRunner has already been installed.
2016-06-10T22:40:35.9884849Z Creating script session...
2016-06-10T22:40:36.1414839Z Adding reference to mscorlib.dll...
2016-06-10T22:40:36.1424839Z Adding reference to System.dll...
2016-06-10T22:40:36.1424839Z Adding reference to System.Core.dll...
2016-06-10T22:40:36.1424839Z Adding reference to System.Data.dll...
2016-06-10T22:40:36.1434839Z Adding reference to System.Xml.dll...
2016-06-10T22:40:36.1434839Z Adding reference to System.Xml.Linq.dll...
2016-06-10T22:40:36.1444839Z Adding reference to Cake.Core.dll...
2016-06-10T22:40:36.1444839Z Adding reference to Cake.Common.dll...
2016-06-10T22:40:36.1444839Z Adding reference to Cake.exe...
2016-06-10T22:40:36.1454832Z Importing namespace Cake.Common...
2016-06-10T22:40:36.1454832Z Importing namespace Cake.Common.Build...
2016-06-10T22:40:36.1464838Z Importing namespace Cake.Common.Build.AppVeyor...
2016-06-10T22:40:36.1464838Z Importing namespace Cake.Common.Build.AppVeyor.Data...
2016-06-10T22:40:36.1464838Z Importing namespace Cake.Common.Build.Bitrise...
2016-06-10T22:40:36.1474848Z Importing namespace Cake.Common.Build.Bitrise.Data...
2016-06-10T22:40:36.1474848Z Importing namespace Cake.Common.Build.ContinuaCI...
2016-06-10T22:40:36.1484838Z Importing namespace Cake.Common.Build.ContinuaCI.Data...
2016-06-10T22:40:36.1484838Z Importing namespace Cake.Common.Build.Jenkins...
2016-06-10T22:40:36.1484838Z Importing namespace Cake.Common.Build.Jenkins.Data...
2016-06-10T22:40:36.1494853Z Importing namespace Cake.Common.Build.TravisCI...
2016-06-10T22:40:36.1494853Z Importing namespace Cake.Common.Build.TravisCI.Data...
2016-06-10T22:40:36.1504839Z Importing namespace Cake.Common.Diagnostics...
2016-06-10T22:40:36.1504839Z Importing namespace Cake.Common.IO...
2016-06-10T22:40:36.1504839Z Importing namespace Cake.Common.IO.Paths...
2016-06-10T22:40:36.1514830Z Importing namespace Cake.Common.Net...
2016-06-10T22:40:36.1544840Z Importing namespace Cake.Common.Security...
2016-06-10T22:40:36.1544840Z Importing namespace Cake.Common.Solution...
2016-06-10T22:40:36.1554836Z Importing namespace Cake.Common.Solution.Project...
2016-06-10T22:40:36.1554836Z Importing namespace Cake.Common.Solution.Project.Properties...
2016-06-10T22:40:36.1564840Z Importing namespace Cake.Common.Solution.Project.XmlDoc...
2016-06-10T22:40:36.1564840Z Importing namespace Cake.Common.Text...
2016-06-10T22:40:36.1564840Z Importing namespace Cake.Common.Tools...
2016-06-10T22:40:36.1574841Z Importing namespace Cake.Common.Tools.Cake...
2016-06-10T22:40:36.1574841Z Importing namespace Cake.Common.Tools.Chocolatey...
2016-06-10T22:40:36.1584834Z Importing namespace Cake.Common.Tools.Chocolatey.ApiKey...
2016-06-10T22:40:36.1584834Z Importing namespace Cake.Common.Tools.Chocolatey.Config...
2016-06-10T22:40:36.1594831Z Importing namespace Cake.Common.Tools.Chocolatey.Features...
2016-06-10T22:40:36.1634824Z Importing namespace Cake.Common.Tools.Chocolatey.Install...
2016-06-10T22:40:36.1644862Z Importing namespace Cake.Common.Tools.Chocolatey.Pack...
2016-06-10T22:40:36.1644862Z Importing namespace Cake.Common.Tools.Chocolatey.Pin...
2016-06-10T22:40:36.1654834Z Importing namespace Cake.Common.Tools.Chocolatey.Push...
2016-06-10T22:40:36.1654834Z Importing namespace Cake.Common.Tools.Chocolatey.Sources...
2016-06-10T22:40:36.1664835Z Importing namespace Cake.Common.Tools.Chocolatey.Upgrade...
2016-06-10T22:40:36.1664835Z Importing namespace Cake.Common.Tools.DNU...
2016-06-10T22:40:36.1664835Z Importing namespace Cake.Common.Tools.DNU.Build...
2016-06-10T22:40:36.1674826Z Importing namespace Cake.Common.Tools.DNU.Pack...
2016-06-10T22:40:36.1674826Z Importing namespace Cake.Common.Tools.DNU.Restore...
2016-06-10T22:40:36.1684837Z Importing namespace Cake.Common.Tools.DotCover...
2016-06-10T22:40:36.1684837Z Importing namespace Cake.Common.Tools.DotCover.Analyse...
2016-06-10T22:40:36.1684837Z Importing namespace Cake.Common.Tools.DotCover.Cover...
2016-06-10T22:40:36.1694839Z Importing namespace Cake.Common.Tools.DotNetCore...
2016-06-10T22:40:36.1694839Z Importing namespace Cake.Common.Tools.DotNetCore.Build...
2016-06-10T22:40:36.1704839Z Importing namespace Cake.Common.Tools.DotNetCore.Execute...
2016-06-10T22:40:36.1704839Z Importing namespace Cake.Common.Tools.DotNetCore.Pack...
2016-06-10T22:40:36.1714838Z Importing namespace Cake.Common.Tools.DotNetCore.Publish...
2016-06-10T22:40:36.1714838Z Importing namespace Cake.Common.Tools.DotNetCore.Restore...
2016-06-10T22:40:36.1724835Z Importing namespace Cake.Common.Tools.DotNetCore.Run...
2016-06-10T22:40:36.1724835Z Importing namespace Cake.Common.Tools.DotNetCore.Test...
2016-06-10T22:40:36.1724835Z Importing namespace Cake.Common.Tools.DupFinder...
2016-06-10T22:40:36.1734832Z Importing namespace Cake.Common.Tools.Fixie...
2016-06-10T22:40:36.1734832Z Importing namespace Cake.Common.Tools.GitLink...
2016-06-10T22:40:36.1744840Z Importing namespace Cake.Common.Tools.GitReleaseManager...
2016-06-10T22:40:36.1744840Z Importing namespace Cake.Common.Tools.GitReleaseManager.AddAssets...
2016-06-10T22:40:36.1744840Z Importing namespace Cake.Common.Tools.GitReleaseManager.Close...
2016-06-10T22:40:36.1754841Z Importing namespace Cake.Common.Tools.GitReleaseManager.Create...
2016-06-10T22:40:36.1754841Z Importing namespace Cake.Common.Tools.GitReleaseManager.Export...
2016-06-10T22:40:36.1764832Z Importing namespace Cake.Common.Tools.GitReleaseManager.Publish...
2016-06-10T22:40:36.1764832Z Importing namespace Cake.Common.Tools.GitReleaseNotes...
2016-06-10T22:40:36.1764832Z Importing namespace Cake.Common.Tools.GitVersion...
2016-06-10T22:40:36.1774831Z Importing namespace Cake.Common.Tools.ILMerge...
2016-06-10T22:40:36.1774831Z Importing namespace Cake.Common.Tools.ILRepack...
2016-06-10T22:40:36.1784836Z Importing namespace Cake.Common.Tools.InspectCode...
2016-06-10T22:40:36.1784836Z Importing namespace Cake.Common.Tools.MSBuild...
2016-06-10T22:40:36.1784836Z Importing namespace Cake.Common.Tools.MSTest...
2016-06-10T22:40:36.1794841Z Importing namespace Cake.Common.Tools.NSIS...
2016-06-10T22:40:36.1794841Z Importing namespace Cake.Common.Tools.NuGet...
2016-06-10T22:40:36.1804837Z Importing namespace Cake.Common.Tools.NuGet.Install...
2016-06-10T22:40:36.1804837Z Importing namespace Cake.Common.Tools.NuGet.Pack...
2016-06-10T22:40:36.1814836Z Importing namespace Cake.Common.Tools.NuGet.Push...
2016-06-10T22:40:36.1814836Z Importing namespace Cake.Common.Tools.NuGet.Restore...
2016-06-10T22:40:36.1814836Z Importing namespace Cake.Common.Tools.NuGet.SetApiKey...
2016-06-10T22:40:36.1824827Z Importing namespace Cake.Common.Tools.NuGet.SetProxy...
2016-06-10T22:40:36.1824827Z Importing namespace Cake.Common.Tools.NuGet.Sources...
2016-06-10T22:40:36.1834837Z Importing namespace Cake.Common.Tools.NuGet.Update...
2016-06-10T22:40:36.1834837Z Importing namespace Cake.Common.Tools.NUnit...
2016-06-10T22:40:36.1834837Z Importing namespace Cake.Common.Tools.OctopusDeploy...
2016-06-10T22:40:36.1844840Z Importing namespace Cake.Common.Tools.OpenCover...
2016-06-10T22:40:36.1844840Z Importing namespace Cake.Common.Tools.ReportGenerator...
2016-06-10T22:40:36.1864836Z Importing namespace Cake.Common.Tools.ReportUnit...
2016-06-10T22:40:36.1874835Z Importing namespace Cake.Common.Tools.Roundhouse...
2016-06-10T22:40:36.1874835Z Importing namespace Cake.Common.Tools.SignTool...
2016-06-10T22:40:36.1874835Z Importing namespace Cake.Common.Tools.SpecFlow...
2016-06-10T22:40:36.1884839Z Importing namespace Cake.Common.Tools.SpecFlow.StepDefinitionReport...
2016-06-10T22:40:36.1884839Z Importing namespace Cake.Common.Tools.SpecFlow.TestExecutionReport...
2016-06-10T22:40:36.1894831Z Importing namespace Cake.Common.Tools.TextTransform...
2016-06-10T22:40:36.1894831Z Importing namespace Cake.Common.Tools.VSTest...
2016-06-10T22:40:36.1904828Z Importing namespace Cake.Common.Tools.WiX...
2016-06-10T22:40:36.1904828Z Importing namespace Cake.Common.Tools.XBuild...
2016-06-10T22:40:36.1924862Z Importing namespace Cake.Common.Tools.XUnit...
2016-06-10T22:40:36.1934850Z Importing namespace Cake.Common.Xml...
2016-06-10T22:40:36.1934850Z Importing namespace Cake.Core...
2016-06-10T22:40:36.1934850Z Importing namespace Cake.Core.Diagnostics...
2016-06-10T22:40:36.1944841Z Importing namespace Cake.Core.IO...
2016-06-10T22:40:36.1944841Z Importing namespace Cake.Core.Scripting...
2016-06-10T22:40:36.1954835Z Importing namespace System...
2016-06-10T22:40:36.1954835Z Importing namespace System.Collections.Generic...
2016-06-10T22:40:36.1964833Z Importing namespace System.IO...
2016-06-10T22:40:36.1964833Z Importing namespace System.Linq...
2016-06-10T22:40:36.1964833Z Importing namespace System.Text...
2016-06-10T22:40:36.1974828Z Importing namespace System.Threading.Tasks...
2016-06-10T22:40:36.1974828Z Compiling build script...
2016-06-10T22:40:39.5864621Z ========================================
2016-06-10T22:40:39.5864621Z Zip-Package
2016-06-10T22:40:39.5874620Z ========================================
2016-06-10T22:40:39.5874620Z Executing task: Zip-Package
2016-06-10T22:40:39.5974627Z ##[error]An error occured when executing task 'Zip-Package'.
**2016-06-10T22:40:39.6014592Z ##[error]Error: System.Exception: AppPackages not exists in the current context --> ./**
2016-06-10T22:40:39.6024618Z ##[error]   at Submission#0.<.ctor>b__12()
2016-06-10T22:40:39.6034607Z ##[error]   at Cake.Core.ActionTask.Execute(ICakeContext context)
2016-06-10T22:40:39.6044619Z ##[error]   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
2016-06-10T22:40:39.6054610Z ##[error]   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
2016-06-10T22:40:39.6104598Z ##[error]   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
2016-06-10T22:40:39.6104598Z ##[error]   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
2016-06-10T22:40:39.6114618Z ##[error]   at Submission#0..ctor(Session session, Object& submissionResult)
2016-06-10T22:40:39.6124615Z ##[error]   at Submission#0.<Factory>(Session session)
2016-06-10T22:40:39.6124615Z ##[error]   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
2016-06-10T22:40:39.6134615Z ##[error]   at Roslyn.Scripting.Session.Execute(String code)
2016-06-10T22:40:39.6134615Z ##[error]   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
2016-06-10T22:40:39.6144621Z ##[error]   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
2016-06-10T22:40:39.6144621Z ##[error]   at Cake.CakeApplication.Run(CakeOptions options)
2016-06-10T22:40:39.6154619Z ##[error]   at Cake.Program.Main()
2016-06-10T22:40:39.6334619Z ##[error]Unexpected exit code 1 returned from tool Cake.exe

**Comment by gep13** [comment]
@dachibox thanks for raising this issue.  Can I get you to re-raise this issue here:

https://github.com/cake-build/cake-vso

As this sounds like an issue with the extension, rather than Cake itself.  Thanks

**Comment by dachibox** [comment]
Hi, of course. Thanks @gep13!
